# Databricks notebook source
# Get environment variable from AKV
env_var = dbutils.secrets.get(scope = 'data-kv-scope', key = 'data-platform-environment')

# COMMAND ----------

# Create the SQL query string
sql_query = f"""
CREATE OR REPLACE TABLE {env_var}_catalog.data_quality.saving_account_test_data AS
SELECT
    '8a9ca04491fcfbf60192006b997b003d' AS SAVING_ACCOUNT_ENCODED_KEY, 
    '8a9ca04491fcfbf6019200666a05003b' AS SAVING_ACCOUNT_HOLDER_KEY,
    '8a9caaf190e171500190e3a179a80001' AS SAVING_ACCOUNT_PRODUCT_TYPE_KEY,
    null AS SAVING_ACCOUNT_ASSIGNED_BRANCH_KEY,
    null AS	SAVING_ACCOUNT_ASSIGNED_USER_KEY,
    null AS	SAVING_ACCOUNT_WITHHOLDING_TAX_SOURCE_KEY,
    2000548302 AS SAVING_ACCOUNT_ID,
    'ACTIVE' AS SAVING_ACCOUNT_STATE,
    'GROUP' AS SAVING_ACCOUNT_HOLDER_TYPE,
    '2 Year FR (TS1) Monthly Income Bond' AS SAVING_ACCOUNT_NAME,
    'GBP' AS SAVING_ACCOUNT_CURRENCY_CODE,
    '2024-09-17' AS	SAVING_ACCOUNT_APPROVED_DATE,
    '2024-09-17' AS	SAVING_ACCOUNT_ACTIVATION_DATE,
    null AS SAVING_ACCOUNT_CLOSE_DATE,
    '2024-11-21' AS SAVING_ACCOUNT_LAST_INTEREST_CALCULATION_DATE,
    '2024-11-01T00:00:00.000+00:00' AS SAVING_ACCOUNT_LAST_INTEREST_STORED_DATETIME,
    '2024-11-21' AS SAVING_ACCOUNT_LAST_ACCOUNT_APPRAISAL_DATE,
    null AS SAVING_ACCOUNT_LAST_INTEREST_REVIEW_DATE,
    1371.5 AS SAVING_ACCOUNT_BALANCE,
    3.41 AS SAVING_ACCRUED_INTEREST,
    0.0 AS ACCRUED_INTEREST_TAX,
    0.0 AS ACCRUED_INTEREST_NET,
    0.0	AS SAVING_ACCOUNT_LOCKED_BALANCE,
    0.0	AS SAVING_ACCOUNT_BLOCKED_BALANCE,
    139	AS LOAD_ID,
    null AS LOAD_DATETIME,
    '2024-11-21T00:00:23Z' AS ROW_START_DATETIME,
    null AS ROW_END_DATETIME,
    1 AS ROW_IS_CURRENT

UNION
SELECT
    '8a9ca13492d8f8c60192e3619aa413ec' AS SAVING_ACCOUNT_ENCODED_KEY,
    '8a9ca13492d8f8c60192e35d34cb13e9' AS SAVING_ACCOUNT_HOLDER_KEY,
    '8a9caaf190e171500190e3a179a80001' AS SAVING_ACCOUNT_PRODUCT_TYPE_KEY,
    null AS SAVING_ACCOUNT_ASSIGNED_BRANCH_KEY,
    null AS SAVING_ACCOUNT_ASSIGNED_USER_KEY,
    null AS SAVING_ACCOUNT_WITHHOLDING_TAX_SOURCE_KEY,
    2004046702 AS SAVING_ACCOUNT_ID,
    'ACTIVE' AS SAVING_ACCOUNT_STATE,
    'GROUP' AS SAVING_ACCOUNT_HOLDER_TYPE,
    '2 Year FR (EP) Monthly Income Bond' AS SAVING_ACCOUNT_NAME,
    'GBP' AS SAVING_ACCOUNT_CURRENCY_CODE,
    '2024-10-31' AS SAVING_ACCOUNT_APPROVED_DATE,
    '2024-10-31' AS SAVING_ACCOUNT_ACTIVATION_DATE,
    null AS SAVING_ACCOUNT_CLOSE_DATE,
    '2024-11-21' AS SAVING_ACCOUNT_LAST_INTEREST_CALCULATION_DATE,
    '2024-11-01T00:00:00Z' AS SAVING_ACCOUNT_LAST_INTEREST_STORED_DATETIME,
    '2024-11-21' AS SAVING_ACCOUNT_LAST_ACCOUNT_APPRAISAL_DATE,
    null AS SAVING_ACCOUNT_LAST_INTEREST_REVIEW_DATE,
    500.61 AS SAVING_ACCOUNT_BALANCE,
    1.15 AS SAVING_ACCRUED_INTEREST,
    0.0 AS ACCRUED_INTEREST_TAX,
    0.0 AS ACCRUED_INTEREST_NET,
    0.0 AS SAVING_ACCOUNT_LOCKED_BALANCE,
    50.0 AS SAVING_ACCOUNT_BLOCKED_BALANCE,
    139 AS LOAD_ID,
    null AS LOAD_DATETIME,
    '2024-11-21T00:00:28Z' AS ROW_START_DATETIME,
    null AS ROW_END_DATETIME,
    1 AS ROW_IS_CURRENT

UNION
SELECT
    '8a9ca8219300d9b10193072caaa32b67' AS SAVING_ACCOUNT_ENCODED_KEY,
    '8a9ca8219300d9b10193072b57d92b64' AS SAVING_ACCOUNT_HOLDER_KEY,
    '8a9caaf190e171500190e3a179a80001' AS SAVING_ACCOUNT_PRODUCT_TYPE_KEY,
    null AS SAVING_ACCOUNT_ASSIGNED_BRANCH_KEY,
    null AS SAVING_ACCOUNT_ASSIGNED_USER_KEY,
    null AS SAVING_ACCOUNT_WITHHOLDING_TAX_SOURCE_KEY,
    2006075102 AS SAVING_ACCOUNT_ID,
    'ACTIVE' AS SAVING_ACCOUNT_STATE,
    'GROUP'	AS SAVING_ACCOUNT_HOLDER_TYPE,
    '2 Year FR (TS1) Monthly Income Bond (365Divider)' AS SAVING_ACCOUNT_NAME,
    'GBP' AS SAVING_ACCOUNT_CURRENCY_CODE,
    '2024-11-07' AS SAVING_ACCOUNT_APPROVED_DATE,
    '2024-11-07' AS	SAVING_ACCOUNT_ACTIVATION_DATE,
    null AS	SAVING_ACCOUNT_CLOSE_DATE,
    '2024-11-21' AS	SAVING_ACCOUNT_LAST_INTEREST_CALCULATION_DATE,
    null AS	SAVING_ACCOUNT_LAST_INTEREST_STORED_DATETIME,
    '2024-11-21' AS	SAVING_ACCOUNT_LAST_ACCOUNT_APPRAISAL_DATE,
    null AS	SAVING_ACCOUNT_LAST_INTEREST_REVIEW_DATE,
    10000.00 AS	SAVING_ACCOUNT_BALANCE,
    30.60 AS SAVING_ACCRUED_INTEREST,
    0.0 AS ACCRUED_INTEREST_TAX,
    0.0 AS ACCRUED_INTEREST_NET,
    0.0	AS SAVING_ACCOUNT_LOCKED_BALANCE,
    0.0	AS SAVING_ACCOUNT_BLOCKED_BALANCE,
    139	AS LOAD_ID,
    null AS	LOAD_DATETIME,
    '2024-11-21T00:00:40Z' AS ROW_START_DATETIME,
    null AS ROW_END_DATETIME,
    1 AS ROW_IS_CURRENT
"""

# Execute the SQL query
spark.sql(sql_query)

# COMMAND ----------


# Create the SQL query string
sql_query = f"""
CREATE OR REPLACE TABLE {env_var}_catalog.data_quality.saving_transaction_test_data AS
SELECT
    '8a9ca13492d8f8c60192d966200c0105' AS SAVING_TRANSACTION_ENCODED_KEY,
    '8a9caaf190e171500190e3a179a80001' AS PRODUCT_TYPE_KEY,
    '8a9ca1ac929c42cb0192af75d96c15aa' AS SAVING_PARENT_ACCOUNT_KEY,
    '8a9ca82690babeff0190baca4a5c000e' AS USER_KEY,
    '8a9ca13492d8f8c60192d966200c0105' AS SAVING_TRANSACTION_KEY,
    '' AS SAVING_TRANSACTION_TYPE,
    null AS TAX_RATE_ENCODEDKEY_OID,
    null AS REVERSAL_SAVING_TRANSACTION_KEY,
    null AS LINKED_SAVING_TRANSACTION_KEY,
    924	AS TRANSACTION_ID,
    '2024-10-29' AS CREATION_DATE,
    166934.55 AS SAVING_TRANSACTION_BALANCE,
    60.9 AS SAVING_TRANSACTION_AMOUNT,
    0.0	AS SAVING_TRANSACTION_INTEREST_AMOUNT,
    0.0	AS SAVING_TRANSACTION_INTEREST_RATE,
    60.9 AS SAVING_TRANSACTION_FUNDS_AMOUNT,
    0 AS SAVING_TRANSACTION_FEES_AMOUNT,
    1 AS SAVING_TRANSACTION_COUNT,
    139	AS LOAD_ID,
    null AS LOAD_DATETIME,
    '2024-09-17T14:01:54Z' AS ROW_START_DATETIME,
    null AS ROW_END_DATETIME,
    1 AS ROW_IS_CURRENT
"""

# Execute the SQL query
spark.sql(sql_query)


# COMMAND ----------

# Create the SQL query string
sql_query = f"""
CREATE OR REPLACE TABLE {env_var}_catalog.data_quality.saving_product_test_data AS
SELECT
    '8a9caaf190e171500190e3a179a80001' AS SAVING_PRODUCT_ENCODED_KEY,
    'FR-TS1-MLYINCBND' AS SAVING_PRODUCT_ID,
    '2 Year FR (TS1) Monthly Income Bond' AS SAVING_PRODUCT_NAME,
    'Yes' AS IS_SAVING_PRODUCT_ACTIVATED,
    'SAVINGS_PLAN' AS SAVING_PRODUCT_TYPE,
    'PERSONAL_DEPOSIT' AS SAVING_PRODUCT_CATEGORY,
    '2 Year FR (TS1) Monthly Income Bond' AS SAVING_PRODUCT_DESCRIPTION,
    139	AS LOAD_ID,
    null AS LOAD_DATETIME,
    '2024-11-19T11:36:16Z' AS ROW_START_DATETIME,
    null AS ROW_END_DATETIME,
    1 AS ROW_IS_CURRENT
"""

# Execute the SQL query
spark.sql(sql_query)


# COMMAND ----------


sql_query = f"""
CREATE OR REPLACE TABLE {env_var}_catalog.data_quality.saving_index_rate_test_data AS
SELECT
    '8a9ca054912465bb019127841e600649' AS SAVING_INDEX_RATE_ENCODED_KEY,
    '8a9ca93f90c7b2010190dacc46950285' AS SAVING_INDEX_RATE_SOURCE_ENCODED_KEY_OID,
    '8a9ca93f90c7b2010190ca42fe7a0004' AS SAVING_INDEX_RATE_USER_KEY,
    5.00 AS SAVING_INDEX_RATE_VALUE,
    139 AS LOAD_ID,
    null AS LOAD_DATETIME,
    null AS ROW_START_DATETIME,
    null AS ROW_END_DATETIME,
    1 AS ROW_IS_CURRENT
"""

# Execute the SQL query
spark.sql(sql_query)


# COMMAND ----------

sql_query = f"""
CREATE OR REPLACE TABLE {env_var}_catalog.data_quality.saving_index_rate_source_test_data AS
SELECT
    '8a9ca93f90c7b2010190cb7b78410256' AS SAVING_INDEX_RATE_SOURCE_ENCODED_KEY,
    'BTLSVR' AS SAVING_INDEX_RATE_SOURCE_ID,
    'BTL SVR' AS SAVING_INDEX_RATE_SOURCE_NAME,
    'INTEREST_RATE' AS SAVING_INDEX_RATE_SOURCE_TYPE,
    139	AS LOAD_ID,
    null AS LOAD_DATETIME,
    null AS ROW_START_DATETIME,
    null AS	ROW_END_DATETIME,
    1 AS ROW_IS_CURRENT

UNION
SELECT
    null AS	SAVING_INDEX_RATE_SOURCE_ENCODED_KEY,
    null AS	SAVING_INDEX_RATE_SOURCE_ID,
    null AS	SAVING_INDEX_RATE_SOURCE_NAME,
    'TAX_RATE' AS SAVING_INDEX_RATE_SOURCE_TYPE,
    null AS LOAD_ID,
    null AS	LOAD_DATETIME,
    null AS	ROW_START_DATETIME,
    null AS	ROW_END_DATETIME,
    null AS	ROW_IS_CURRENT

UNION 
SELECT
    null AS	SAVING_INDEX_RATE_SOURCE_ENCODED_KEY,
    null AS	SAVING_INDEX_RATE_SOURCE_ID,
    null AS	SAVING_INDEX_RATE_SOURCE_NAME,
    'WITHHOLDING_TAX_RATE' AS SAVING_INDEX_RATE_SOURCE_TYPE,
    null AS LOAD_ID,
    null AS	LOAD_DATETIME,
    null AS	ROW_START_DATETIME,
    null AS	ROW_END_DATETIME,
    null AS	ROW_IS_CURRENT
"""

# Execute the SQL query
spark.sql(sql_query)


# COMMAND ----------

sql_query = f"""
CREATE OR REPLACE TABLE {env_var}_catalog.data_quality.user_test_data AS
SELECT
    '8a9ca82690babeff0190baca4a5c000e' AS USER_ENCODED_KEY,
    null AS	ASSIGNED_BRANCH_KEY,
    '31' AS	USER_ID,
    null AS	USER_TITLE,
    'TS0SharedKey' AS USER_USERNAME,
    null AS	USER_FIRST_NAME,
    null AS	USER_LAST_NAME,
    'ACTIVE' AS	USER_STATE,
    '2024-07-16' AS	CREATION_DATE,
    '2024-07-16T09:40:39Z' AS CREATION_DATETIME,
    '2024-09-10' AS	LAST_MODIFIED_DATE,
    '2024-09-10T16:03:35Z' AS LAST_MODIFIED_DATETIME,
    139	AS LOAD_ID,
    null AS LOAD_DATETIME,
    '2024-09-10T16:03:35Z' AS ROW_START_DATETIME,
    null AS ROW_END_DATETIME,
    1 AS ROW_IS_CURRENT
"""

# Execute the SQL query
spark.sql(sql_query)


# COMMAND ----------

sql_query = f"""
CREATE OR REPLACE TABLE {env_var}_catalog.data_quality.saving_payment_detail_test_data AS
SELECT
    '8a9ca13492d8f8c60192d966200c0107' AS SAVING_PAYMENT_DETAIL_ENCODED_KEY,
    '8a9ca13492d8f8c60192d966200c0105' AS SAVING_TRANSACTION_KEY,
    null AS	CREDITOR_ACCOUNT_IBAN,
    'ANDREW FAIRHURST' AS CREDITOR_NAME,
    null AS	CREDITOR_ACCOUNT_CURRENCY,
    null AS	DEBTOR_ACCOUNT_IBAN,
    null AS	DEBTOR_NAME,
    null AS	DEBTOR_ACCOUNT_CURRENCY,
    139	AS LOAD_ID,
    null AS	LOAD_DATETIME,
    null AS ROW_START_DATETIME,
    null AS ROW_END_DATETIME,
    1 AS ROW_IS_CURRENT
"""

# Execute the SQL query
spark.sql(sql_query)

