SELECT
  CAST(UPPER(u.u_id) AS STRING) AS USERS_ID,
  CAST(UPPER(u.u_tid)AS BIGINT) AS USERS_TID,
  CAST(UPPER(u.aa_id) AS STRING) AS AUDIT_ARTICLES_ID,
  CAST(UPPER(u.gp_id) AS STRING) AS GP_ID,
  CAST(UPPER(u.sp_id) AS STRING) AS SP_ID,
  CAST(UPPER(u.subjectId) AS STRING) AS SUBJECT_ID,  
  CAST((u.fullName) AS STRING) AS FULL_NAME,
  CAST((u.version) AS INT) AS USERS_VERSION,
  CAST((u.migrationCode) AS BINARY) AS MIGRATION_CODE,
  CAST((u.isDeleted) AS TINYINT) AS IS_DELETED,
  CAST((u.isTemplate) AS TINYINT) AS IS_TEMPLATE,
  CAST(u.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(u.MDP_LOAD_ID AS INT) AS MDP_LOAD_ID,
  CAST(u.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(u.MDP_LOAD_TYPE AS STRING) AS MDP_LOAD_TYPE
FROM {env_var}_catalog.bronze_spectra_con.users u
 
 
 