SELECT
  de.DATA_ENTITY_ID AS BK_WORKFLOW_CUSTOMER,
  de.STR_VALUE AS CUSTOMER_NUMBER,
  'SPECTRA' AS SOURCE_SYSTEM,
  getdate () AS ROW_START_DATETIME,
  CAST(NULL AS TIMESTAMP) AS ROW_END_DATETIME,
  1 AS ROW_IS_CURRENT
FROM {env_var}_catalog.silver_int.spectra_work_item_data_entities de
WHERE de.DATA_ELEMENT_ID = 1209
AND de.ROW_END_DATETIME IS NULL
;