SELECT
  c.CHANNELS_ID AS BK_WORKFLOW_CHANNEL,
  coalesce(c.CHANNELS_NAME, 'Unknown') as CHANNELS_NAME,
  CASE WHEN c.IS_INBOUND = 1 THEN 'Yes' WHEN c.IS_INBOUND= 0 THEN 'No' Else 'Unknown' End as IS_INBOUND,
  CASE WHEN c.IS_OUTBOUND = 1 THEN 'Yes' When c.IS_OUTBOUND= 0 THEN 'No' Else 'Unknown' End as IS_OUTBOUND,
  c.DEFAULT_OUTBOUND_CHANNEL_ID AS DEFAULT_OUTBOUND_CHANNEL_IDENTIFIER,
  c.INITIAL_OFFERS_SLA,
  c.INITIAL_OFFER_PRIORITY_SLA,
  'SPECTRA' AS SOURCE_SYSTEM,
  CURRENT_TIMESTAMP() AS ROW_START_DATETIME,
  CAST(NULL AS TIMESTAMP) AS ROW_END_DATETIME,
  1 AS ROW_IS_CURRENT
FROM {env_var}_catalog.silver_int.spectra_channels c
;