SELECT
  so.OUTCOME_ID AS BK_WORKFLOW_OUTCOME,
  COALESCE(so.OUTCOME_NAME, 'Unknown') AS OUTCOME_NAME,
  COALESCE(so.OUTCOME_SHORT_NAME, 'Unknown') AS OUTCOME_SHORT_NAME,
  COALESCE(so.OUTCOME_DESCRIPTION, 'Unknown') AS OUTCOME_DESCRIPTION,
  CASE WHEN so.SLA_OFFSET = 1 THEN 'Yes' 
  WHEN so.SLA_OFFSET = 0 THEN 'No' ELSE 'Unknown' END AS IS_SLA_OFFSET,
  COALESCE(so.EXPECTED_WORK_TIME, -2) AS EXPECTED_WORK_TIME,
  CASE WHEN CAST(so.IS_TRIGGER_CHECKPOINT AS boolean) = 'true' then 'Yes' else 'No' END AS IS_TRIGGER_CHECKPOINT,
  CASE WHEN CAST(so.IS_RECORD_OUTCOME AS boolean) = 'true' then 'Yes' else 'No' END AS IS_RECORD_OUTCOME,
  CASE WHEN CAST(so.IS_PROCESS_ASYNC AS boolean) = 'true' then 'Yes' else 'No' END AS IS_PROCESS_ASYNC,
  CASE WHEN CAST(so.IS_OFFER_PROCESS_ASYNC AS boolean) = 'true' then 'Yes' else 'No' END AS IS_OFFER_PROCESS_ASYNC,
  CASE WHEN CAST(so.IS_COMMIT_PROCESS_ASYNC AS boolean) = 'true' then 'Yes' else 'No' END AS IS_COMMIT_PROCESS_ASYNC,
  CASE WHEN CAST(so.IS_DELETED AS boolean) = 'true' then 'Yes' else 'No' END AS IS_DELETED,
  so.SLA_OFFSET_DAYS,
  CASE WHEN CAST(so.HAS_DATA_FORM_PRECEDENCE AS boolean) = 'true' then 'Yes' else 'No' END AS HAS_DATA_FORM_PRECEDENCE,
  'SPECTRA' AS SOURCE_SYSTEM,
  getdate() AS ROW_START_DATETIME,
  CAST(NULL AS timestamp) AS ROW_END_DATETIME,
  1 AS ROW_IS_CURRENT
FROM {env_var}_catalog.silver_int.spectra_outcomes so
;