SELECT
  wide.DATA_ENTITY_ID AS BK_WORKFLOW_ACCOUNT,
  wide.STR_VALUE AS ACCOUNT_NUMBER,
  'SPECTRA' AS SOURCE_SYSTEM,
  getdate() AS ROW_START_DATETIME,
  CAST(NULL AS TIMESTAMP) AS ROW_END_DATETIME,
  1 AS ROW_IS_CURRENT
FROM {env_var}_catalog.silver_int.spectra_work_item_data_entities wide
WHERE wide.DATA_ELEMENT_ID = 1197
AND wide.ROW_END_DATETIME IS NULL
;