SELECT
sc.COMPANIES_ID AS BK_WORKFLOW_BUSINESS_STREAM,
sc.COMPANIES_NAME AS BUSINESS_STREAM_NAME,
CASE 
    WHEN sc.IS_DELETED = 1 THEN 'Yes'
    WHEN sc.IS_DELETED = 0 THEN 'No'
    WHEN sc.IS_DELETED IS NULL THEN 'Unknown'
END AS IS_DELETED,
'SPECTRA' AS SOURCE_SYSTEM,
GETDATE() AS ROW_START_DATETIME,
CAST(NULL AS TIMESTAMP) AS ROW_END_DATETIME,
1 AS ROW_IS_CURRENT
FROM {env_var}_catalog.silver_int.spectra_companies sc
;