SELECT
  CAST(UPPER(a.AdvisorId) AS STRING) AS ADVISOR_ID,
  CAST(UPPER(a.CaseId) AS STRING) AS CASE_ID,
  CAST(a.FirmFcaNumber AS BIGINT) AS FIRM_FCA_NUMBER,
  CAST(a.IntermediaryFirm AS STRING) AS INTERMEDIARY_FIRM,
  CAST(a.IntermediaryName AS STRING) AS INTERMEDIARY_NAME,
  CAST(a.PaymentRoute AS STRING) AS PAYMENT_ROUTE,
  CAST(a.LevelOfService AS STRING) AS LEVEL_OF_SERVICE,
  CAST(a.FeeChargedToApplicant AS DECIMAL(6, 2)) AS FEE_CHARGED_TO_APPLICANT,
  CAST(a.ReferenceNumber AS STRING) AS REFERENCE_NUMBER,
  CAST(a.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(a.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(a.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(a.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(a.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(a.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_con.advisor a
WHERE a.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1