SELECT
  CAST(UPPER(ce.CaseId) AS STRING) AS CASE_ID,
  CAST(ce.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(ce.Description AS STRING) AS DESCRIPTION,
  CAST(ce.Amount AS DECIMAL(10, 2)) AS AMOUNT,
  CAST(ce.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(ce.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(ce.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(ce.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(ce.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME 
FROM {env_var}_catalog.bronze_mso_con.committed_expenditure ce
WHERE ce.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1