SELECT
  CAST(UPPER(cev.CommittedExpenditureValueId) AS STRING) AS COMMITTED_EXPENDITURE_VALUE_ID,
  CAST(UPPER(cev.CaseId) AS STRING) AS CASE_ID,
  CAST(cev.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(cev.Description AS STRING) AS DESCRIPTION,
  -- Renaming because PROVIDER is a reserved keyword
  CAST(cev.Provider AS STRING) AS CREDIT_FACILITY_PROVIDER,
  CAST(cev.Amount AS DECIMAL(6, 2)) AS AMOUNT,
  CAST(cev.RegularMonthlyPayment AS DECIMAL(10, 2)) AS REGULAR_MONTHLY_PAYMENT_AMOUNT,
  CAST(cev.FutureMonthlyPayment AS DECIMAL(6, 2)) AS FUTURE_MONTHLY_PAYMENT_AMOUNT,
  CAST(cev.OngoingMonthlyPayment AS DECIMAL(6, 2)) AS ONGOING_MONTHLY_PAYMENT_AMOUNT,
  CAST(cev.BalanceBeingPaid AS DECIMAL(10, 2)) AS BALANCE_BEING_PAID,
  CAST(cev.CurrentBalanceOwing AS DECIMAL(10, 2)) AS CURRENT_BALANCE_OWING,
  CAST(cev.HighestBalanceOwing AS DECIMAL(19, 2)) AS HIGHEST_BALANCE_OWING,
  CAST(cev.IsBalanceBeingCleared AS TINYINT) AS IS_BALANCE_BEING_CLEARED,
  CAST(cev.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(cev.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(cev.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(cev.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(cev.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME 
FROM {env_var}_catalog.bronze_mso_con.committed_expenditure_value cev
WHERE cev.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1