SELECT
  CAST(UPPER(da.DeclineAppealId) AS STRING) AS DECLINE_APPEAL_ID,
  CAST(UPPER(da.CaseId) AS STRING) AS CASE_ID,
  CAST(UPPER(da.DecisionId) AS STRING) AS DECISION_ID,
  CAST(UPPER(da.TaskId) AS STRING) AS TASK_ID,
  CAST(UPPER(da.CreatedByUserId) AS STRING) AS CREATED_BY_USER_ID,
  CAST(da.CreatedDate AS TIMESTAMP) AS CREATED_DATETIME,
  CAST(da.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(da.Title AS STRING) AS TITLE,
  -- Renaming as TEXT is a reserved keyword
  CAST(da.Text AS STRING) AS APPEAL_REASON,
  CAST(da.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(da.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(da.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(da.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(da.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME 
FROM {env_var}_catalog.bronze_mso_con.decline_appeal da
WHERE da.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1