SELECT
  CAST(dr.TableName AS STRING) AS TABLE_NAME,
  CAST(dr.KeyName1 AS STRING) AS KEY_NAME_1,
  CAST(dr.KeyValue1 AS STRING) AS KEY_VALUE_1,
  CAST(dr.KeyName2 AS STRING) AS KEY_NAME_2,
  CAST(dr.KeyValue2 AS STRING) AS KEY_VALUE_2,
  CAST(dr.KeyName3 AS STRING) AS KEY_NAME_3,
  CAST(dr.KeyValue3 AS STRING) AS KEY_VALUE_3,
  CAST(dr.KeyName4 AS STRING) AS KEY_NAME_4,
  CAST(dr.KeyValue4 AS STRING) AS KEY_VALUE_4,
  CAST(dr.KeyName5 AS STRING) AS KEY_NAME_5,
  CAST(dr.KeyValue5 AS STRING) AS KEY_VALUE_5,
  CAST(dr.KeyName6 AS STRING) AS KEY_NAME_6,
  CAST(dr.KeyValue6 AS STRING) AS KEY_VALUE_6,
  CAST(dr.DateDeletedFromPublished AS TIMESTAMP) AS DATE_DELETED_FROM_PUBLISHED,
  CAST(dr.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(dr.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(dr.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(dr.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(dr.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(dr.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME 
FROM {env_var}_catalog.bronze_mso_con.deleted_record dr
WHERE dr.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1