/*LF Note: Lots of column renames in here to make them more
explicit. Many are open to interpretation. Definitions taken
from IRESS MSO Data Dictionary.*/
SELECT
  CAST(UPPER(epa.ExistingPropertyId) AS STRING) AS EXISTING_PROPERTY_ID,
  CAST(epa.AddressType AS STRING) AS ADDRESS_TYPE,
  CAST(UPPER(epa.CareOfSurname) AS STRING) AS CARE_OF_SURNAME,
  CAST(UPPER(epa.BfpoNumber) AS STRING) AS BRITISH_FORCES_POST_OFFICE_NUMBER,
  CAST(UPPER(epa.BuildingName) AS STRING) AS BUILDING_NAME,
  CAST(UPPER(epa.BuildingNo) AS STRING) AS BUILDING_NUMBER,
  CAST(UPPER(epa.Flat) AS STRING) AS FLAT,
  CAST(UPPER(epa.Street) AS STRING) AS STREET,
  CAST(UPPER(epa.Line1) AS STRING) AS ADDRESS_LINE_1,
  CAST(UPPER(epa.Line2) AS STRING) AS ADDRESS_LINE_2,
  CAST(UPPER(epa.Line3) AS STRING) AS ADDRESS_LINE_3,
  CAST(UPPER(epa.Line4) AS STRING) AS ADDRESS_LINE_4,
  CAST(UPPER(epa.Line5) AS STRING) AS ADDRESS_LINE_5,
  CAST(UPPER(epa.Line6) AS STRING) AS ADDRESS_LINE_6,
  CAST(UPPER(epa.District) AS STRING) AS DISTRICT,
  CAST(UPPER(epa.Town) AS STRING) AS TOWN,
  CAST(UPPER(epa.County) AS STRING) AS COUNTY,
  CAST(UPPER(epa.Postcode) AS STRING) AS POSTCODE, 
  CAST(UPPER(epa.OperationName) AS STRING) AS BRITISH_FORCES_OPERATION_NAME,
  CAST(UPPER(epa.Rank) AS STRING) AS BRITISH_FORCES_RANK,
  CAST(UPPER(epa.ServiceNumber) AS STRING) AS BRITISH_FORCES_SERVICE_NUMBER,
  CAST(UPPER(epa.Unit) AS STRING) AS BRITISH_FORCES_UNIT,
  CAST(epa.CountryTypeCode AS STRING) AS COUNTRY_TYPE_CODE,
  CAST(epa.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(epa.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(epa.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(epa.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(epa.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(epa.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_con.existing_property_address epa
WHERE epa.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1