SELECT
  CAST(UPPER(epa.ExistingPropertyId) AS STRING) AS EXISTING_PROPERTY_ID,
  CAST(UPPER(epa.ApplicantId) AS STRING) AS APPLICANT_ID,
  CAST(epa.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(epa.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(epa.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(epa.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(epa.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(epa.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_con.existing_property_applicant epa
WHERE epa.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1