SELECT
  CAST(UPPER(ft.FeeTransactionId) AS STRING) AS FEE_TRANSACTION_ID,
  CAST(UPPER(ft.FeeId) AS STRING) AS FEE_ID,
  CAST(UPPER(ft.ReceiptId) AS STRING) AS RECEIPT_ID,
  CAST(ft.ExternalReference AS STRING) AS EXTERNAL_REFERENCE,
  CAST(ft.TransactionAmount AS DECIMAL(6, 2)) AS TRANSACTION_AMOUNT,
  CAST(ft.TransactionType AS STRING) AS TRANSACTION_TYPE,
  CAST(ft.TransactionStatus AS STRING) AS TRANSACTION_STATUS,
  CAST(ft.Notes AS STRING) AS NOTES,
  CAST(ft.CreatedBy AS STRING) AS CREATED_BY_USER,
  CAST(ft.TransactionDate AS TIMESTAMP) AS TRANSACTION_DATETIME,
  CAST(ft.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(ft.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(ft.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(ft.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(ft.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(ft.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_con.fee_transaction ft
WHERE ft.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1