SELECT
  CAST(UPPER(ivd.IdentityVerificationDocumentId) AS STRING) AS IDENTITY_VERIFICATION_DOCUMENT_ID,
  CAST(UPPER(ivd.ApplicantId) AS STRING) AS APPLICANT_ID,
  CAST(UPPER(ivd.AssetVersionId) AS STRING) AS ASSET_VERSION_ID,
  CAST(ivd.TypeName AS STRING) AS DOCUMENT_TYPE_NAME,
  CAST(ivd.Reference AS STRING) AS REFERENCE,
  CAST(ivd.AssetName AS STRING) AS ASSET_NAME,
  CAST(ivd.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(ivd.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(ivd.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(ivd.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(ivd.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(ivd.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_con.identity_verification_document ivd
WHERE ivd.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1