SELECT
  CAST(UPPER(ce.CaseEventId) AS STRING) AS CASE_EVENT_ID,
  CAST(UPPER(ce.CaseId) AS STRING) AS CASE_ID,
  CAST(ce.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(ce.Category AS STRING) AS CATEGORY,
  -- Using "EVENT_NAME" instead of "NAME" because "NAME" is a reserved keyword
  CAST(ce.Name AS STRING) AS EVENT_NAME,
  CAST(ce.ReasonForStatus AS STRING) AS REASON_FOR_STATUS,
  CAST(UPPER(ce.CreatedBy) AS STRING) AS CREATED_BY,
  from_json(
    ce.ResourceFormatItems,
    "ARRAY<STRING>"
  ) AS RESOURCE_FORMAT_ITEMS,
  CAST(ce.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(ce.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(ce.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(ce.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(ce.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_con.case_event ce
WHERE ce.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1