SELECT
  CAST(UPPER(nac.Id) AS STRING) AS NEED_AND_CIRCUMSTANCE_ID,
  CAST(UPPER(nac.CaseId) AS STRING) AS CASE_ID,
  CAST(nac.Question AS STRING) AS QUESTION,
  CAST(nac.Answer AS STRING) AS ANSWER,
  CAST(nac.Score AS INT) AS SCORE,
  CAST(nac.PageId AS INT) AS PAGE_ID,
  CAST(nac.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(nac.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(nac.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(nac.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(nac.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(nac.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_con.need_and_circumstance nac
WHERE nac.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1