SELECT
  CAST(UPPER(oco.OriginationsCaseOwnerId) AS STRING) AS ORIGINATIONS_CASE_OWNER_ID,
  CAST(UPPER(oco.CaseId) AS STRING) AS CASE_ID,
  CAST(UPPER(oco.OwnerId) AS STRING) AS OWNER_ID,
  CAST(UPPER(oco.OwnerName) AS STRING) AS OWNER_NAME,
  CAST(oco.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(oco.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(oco.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(oco.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(oco.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(oco.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_con.originations_case_owner oco
WHERE oco.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1