SELECT
  CAST(UPPER(m.Id) AS STRING) AS ORIGINATIONS_USER_ID,
  CAST(UPPER(m.Forename) AS STRING) AS ORIGINATIONS_USER_FORENAME,
  CAST(UPPER(m.Surname) AS STRING) AS ORIGINATIONS_USER_SURNAME,
  CAST(UPPER(m.Reference) AS STRING) AS ORIGINATIONS_USER_REFERENCE,
  CAST(m.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(m.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(m.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(m.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(m.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(m.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_con.member m
WHERE m.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1