# Databricks notebook source
import dlt
from pyspark.sql.functions import row_number, col, expr
from pyspark.sql.window import Window
import mdp_databricks_common.silver_layer_functions as dlf

env_var = dbutils.secrets.get(scope = 'data-kv-scope', key = 'data-platform-environment')

# COMMAND ----------

@dlt.table(
    name = "sunrise_users",
    comment = "List of users who respond to incidents. Columns renamed to naming convention"
)
@dlt.expect("SERVICEREQNO is not null", "SERVICEREQNO IS NOT NULL")
def silver_sunrise_users():

    df = spark.sql(f"""
    SELECT  
    SERVICEREQNO AS SERVICEREQNO,
    SERVICEREQID AS USER_ID,
    NAME AS USER_LAST_NAME,
    STATEID AS STATE_ID,
    LIFECYCLEID AS LIFECYCLE_ID,
    ADDEDDATE AS ADDED_DATE_TIME,
    ADDEDBY AS ADDED_BY,
    UPDATEDDATE AS UPDATED_DATE_TIME,
    UPDATEDBY AS UPDATED_BY,
    SYSACCOUNTNAME AS SYS_ACCOUNT_NAME,
    SYSACCOUNTDESC AS SYS_ACCOUNT_DESC,
    EXTERNALACCOUNT AS EXTERNAL_ACCOUNT,
    PASSWORDLASTCHNGD AS PASSWORD_LAST_CHANGED,
    STATUS AS STATUS_FLAG,
    DELETESTATUS AS DELETE_STATUS_FLAG,
    OWNERACCOUNT AS OWNER_ACCOUNT,
    OWNERGROUP AS OWNER_GROUP,
    ACCOUNTNAME AS ACCOUNT_NAME,
    ADDEDZONE AS ADDED_ZONE,
    UPDATEDZONE AS UPDATED_ZONE,
    EMAIL AS EMAIL_ADDRESS,
    TELEPHONE AS TELEPHONE_NUMBER,
    FAX AS FAX,
    MOBILE AS MOBILE_NUMBER,
    `A#112001126` AS `A#112001126`, -- needs renaming once LBS confirm
    EXTENSION AS EXTENSION,
    JOBTITLE AS JOB_TITLE,
    TITLE AS TITLE,
    NETWORKLOGON AS NETWORK_LOGON,
    ATTACHMENTS AS ATTACHEMENTS,
    RETURNDATE AS RETURN_DATE_TIME,
    MAILBOX AS MAILBOX,
    NOINC AS NO_INC,
    GRAPHIC AS GRAPHIC,
    ASSOCIATION AS ASSOCIATION,
    TWITTERID AS TWITTER_ID,
    CHATTERID AS CHATTER_ID,
    FACEBOOKID AS FACEBOOK_ID,
    LINKEDINID AS LINKEDIN_ID,
    TWITTERTOKEN AS TWITTER_TOKEN,
    TWITTERSECRET AS TWITTER_SECRET,
    FORENAME AS USER_FORENAME,
    `H#SERVICEREQID0` AS CONTACT_ID,
    `H#112001185` AS `H#112001185`, -- needs renaming once LBS confirm
    UNIQUEID AS UNIQUE_ID,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    MDP_LOAD_DATETIME,
    __START_AT AS ROW_START_DATETIME,
    __END_AT AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_sunrise_con.users
""")

    # Define the window specification
    windowSpec = dlf.get_window_spec("SERVICEREQNO", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df

# COMMAND ----------

@dlt.table(
    name = "sunrise_incidents",
    comment = "Incidents raised to Sunrise IT Helpdesk System. Columns renamed to conform to naming conventions"
)
@dlt.expect("SERVICEREQNO is not null", "SERVICEREQNO IS NOT NULL")
def silver_sunrise_incidents():

    df = spark.sql(f"""
    SELECT  
    SERVICEREQNO AS SERVICEREQNO,
    SERVICEREQID AS INCIDENTS_ID,
    NAME AS INCIDENT_NAME,
    DESCRIPTION AS INCIDENT_DESCRIPTION,
    STATEID AS STATE_ID,
    LIFECYCLEID AS LIFECYCLE_ID,
    ADDEDDATE AS ADDED_DATE_TIME,
    ADDEDBY AS ADDED_BY,
    UPDATEDDATE AS UPDATED_DATE_TIME,
    UPDATEDBY AS UPDATED_BY,
    OWNERACCOUNT AS OWNER_ACCOUNT,
    PRIORITY AS PRIORITY,
    ESCALATIONLEVEL AS ESCALATION_LEVEL,
    `H#112001104` AS `H#112001104`, -- needs renaming once LBS confirm
    `H#NAME1` AS CONTACT_DEPARTMENT_NAME,
    `H#NAME2` AS PR_SERVICE_LEVEL_NAME,
    `H#NAME3` AS ITEM_NAME,
    FASTFIX AS FAST_FIX,
    CATEGORY1 AS CATEGORY_1,
    CATEGORY2 AS CATEGORY_2,
    ACTIVETIME AS ACTIVE_TIME,
    RESPTIME AS RESPONSE_TIME,
    RESPDT AS RESPONSE_DATE_TIME,
    RESLTIME AS RESOLUTION_TIME,
    RESLDT AS RESOLUTION_DATE_TIME,
    RESPTGTDT AS RESPONSE_TARGET_DATE,
    RESLTGTDT AS RESOLUTION_TARGET_DATE,
    TORESPTIME AS TOTAL_RESPONSE_TIME,
    TORESLTIME AS TOTAL_RESOLUTION_TIME,
    TORESPTIMEEXC AS TOTAL_RESPONSE_TIME_EXCEEDED,
    TORESLTIMEEXC AS TOTAL_RESOLUTION_TIME_EXCEEDED,
    `H#112001106` AS `H#112001106`, -- needs renaming once LBS confirm
    CLOSEDDT AS CLOSED_DATE_TIME,
    ABORTEDDT AS ABORTED_DATE_TIME,
    HELDDT AS HELD_DATE_TIME,
    ARCHIVEDDT AS ARCHIVED_DATE_TIME,
    TPABORTDT AS SUPPLIER_ABORT_DATE,
    TPCLOSEDT AS SUPPLIER_CLOSE_DATE,
    OPENDT AS OPEN_DATE,
    `H#WARRANTYENDDT0` AS ITEM_WARRENTY_END_DATE,
    BOUNCECOUNT AS BOUNCE_COUNT,
    IMPACT AS IMPACT,
    `A#112001114` AS `A#112001114`,  -- needs renaming once LBS confirm
    RELEASEDT AS RELEASE_DATE_TIME,
    CATEGORY3 AS CATEGORY_3,
    GROUPTEXT AS GROUP_TEXT,
    RESOLVEDT AS RESOLVE_DATE_TIME,
    PARTNERREF AS PARTNER_REF,
    URGENCY AS URGENCY,
    URGENCYTEXT AS URGENCY_DESCRIPTION,
    IMPACTTEXT AS IMPACT_DESCRIPTION,
    SLATOUSE AS SLA,
    INCIDENTSOURCE AS INCIDENT_SOURCE,
    RESOLVEDBY1 AS RESOLVED_BY_1,
    CUSTMESCALATION AS CUSTOMER_ESCALATION_FLAG,
    MAILPROCESSOR AS MAIL_PROCESSER,
    MBRDETRIMENT2 AS MEMBER_DETRIMENT_FLAG,
    `H#NAME10` AS LOCATION_NAME,
    TRIAGESLABRCCNT AS TRIAGE_SLA_BREACH_COUNT,
    DESKVISITREQ AS DESK_VISIT_REQUIRED_FLAG,
    RESOLVECAUSETYP AS RESOLVE_CAUSE_TYPE,
    CLOSETYPE1 AS CLOSE_TYPE_1,
    RESOLVETYPE1 AS RESOLVE_TYPE_1,
    REGIMPACT AS REG_IMPACT,
    ISPRIORITYINCID AS IS_PRIORITY_INCIDENT_ID,
    CHILDINCIDENT AS CHILD_INCIDENT,
    `A#112001120` AS `A#112001120`, -- needs renaming once LBS confirm
    `A#112001248` AS `A#112001248`, -- needs renaming once LBS confirm
    MASTERINCIDENT AS MASTER_INCIDENT,
    RESOLVEDBY2 AS RESOLVED_BY_2,
    COVID19 AS COVID19,
    COMMSSLABRCHCNT AS COMMS_SLA_BRCH_CNT,
    TECHNICALRES AS TECHNICAL_RES,
    `H#SERVICEREQID0` AS `H#SERVICEREQID0`,
    REQUESTTYPE AS REQUEST_TYPE,
    BREACHGROUP AS BREACH_GROUP,
    BREACHASSIGNEE AS BREACH_ASSIGNEE,
    NSFSTARTDATE AS NSF_START_DATE,
    FEEDBACK AS FEEDBACK,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    MDP_LOAD_DATETIME,
    __START_AT AS ROW_START_DATETIME,
    __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_sunrise_con.incidents
""")

    # Define the window specification
    windowSpec = dlf.get_window_spec("SERVICEREQNO", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df
