# Databricks notebook source
import dlt
from pyspark.sql.functions import row_number, col, expr
from pyspark.sql.window import Window
import mdp_databricks_common.silver_layer_functions as dlf

env_var = dbutils.secrets.get(scope = 'data-kv-scope', key = 'data-platform-environment')

# COMMAND ----------

@dlt.table(
    name = "sunrise_lookup",
    comment = "lookup table for most dimensions in itsm data model."
)
@dlt.expect("FIELDID is not null", "FIELDID IS NOT NULL")
def silver_sunrise_lookup():
    df = spark.sql(f"""
    SELECT  
    FIELDID AS FIELDID,
    LANGUAGEID AS LANGUAGE_ID,
    ACTUALVALUE AS ACTUAL_VALUE,
    COSMETICVALUE AS DESCRIPTION,
    DELETEFLAG AS DELETE_FLAG,
    IMAGEPATH AS IMAGE_PATH,
    DEFAULTVALUE AS DEFAULT_VALUE,
    SORTORDER AS SORT_ORDER,
    PARENTACTUALVALUE AS PARENT_ACTUAL_VALUE,
    PREFIXEDDATA AS PREFIXED_DATA,
    SEQUENCENUMBER AS SEQUENCE_NUMBER,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    MDP_LOAD_DATETIME
    FROM {env_var}_catalog.bronze_sunrise_int.s_fld_defaultdata
    """)

    # Define the window specification
    windowSpec = dlf.get_window_spec("FIELDID", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df

# COMMAND ----------

@dlt.table(
    name = "sunrise_state",
    comment = "lookup stable for incident states"
)
@dlt.expect("STATEID is not null", "STATEID IS NOT NULL")
def silver_sunrise_state():
    df = spark.sql(f"""
    SELECT  
    STATEID AS STATEID,
    LANGUAGEID AS LANGUAGE_ID,
    NAME AS INCIDENT_STATE,
    DESCRIPTION AS INCIDENT_DESCRIPTION,
    ICON AS ICON,
    TOOLTIPTEXT AS TOOL_TIP_TEXT,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    MDP_LOAD_DATETIME
    FROM {env_var}_catalog.bronze_sunrise_int.s_state_l
    """)

    # Define the window specification
    windowSpec = dlf.get_window_spec("STATEID", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df

# COMMAND ----------

@dlt.table(
    name = "sunrise_team",
    comment = "Internal team's"
)
@dlt.expect("GROUPID is not null", "GROUPID IS NOT NULL")
def silver_sunrise_team():
    df = spark.sql(f"""
    SELECT  
    GROUPID AS GROUPID,
    LANGUAGEID AS LANGUAGE_ID,
    NAME AS TEAM_NAME,
    DESCRIPTION AS TEAM_DESCRIPTION,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    MDP_LOAD_DATETIME
    FROM {env_var}_catalog.bronze_sunrise_int.s_groups_l
    """)

    # Define the window specification
    windowSpec = dlf.get_window_spec("GROUPID", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df

# COMMAND ----------

@dlt.table(
    name = "sunrise_contact",
    comment = "List of people raising IT helpdesk incidents."
)
@dlt.expect("SERVICEREQNO is not null", "SERVICEREQNO IS NOT NULL")
def silver_sunrise_contact():
    df = spark.sql(f"""
    SELECT  
    SERVICEREQNO AS SERVICEREQNO,
    SERVICEREQID AS CONTACT_ID,
    NAME AS CONTACT_NAME,
    DESCRIPTION AS CONTACT_DESCRIPTION,
    STATEID AS STATE_ID,
    LIFECYCLEID AS LIFECYCLE_ID,
    ADDEDDATE AS ADDED_DATE_TIME,
    ADDEDBY AS ADDED_BY,
    UPDATEDDATE AS UPDATED_DATE_TIME,
    UPDATEDBY AS UPDATED_BY,
    SYSACCOUNTNAME AS SYS_ACCOUNT_NAME,
    SYSACCOUNTDESC AS SYS_ACCOUNT_DESC,
    EXTERNALACCOUNT AS EXTERNAL_ACCOUNT,
    PASSWORDLASTCHNGD AS PASSWORD_LAST_CHANGED,
    STATUS AS STATUS_FLAG,
    DELETESTATUS AS DELETE_STATUS_FLAG,
    OWNERACCOUNT AS OWNER_ACCOUNT,
    OWNERGROUP AS OWNER_GROUP,
    INITIALS AS INITIALS,
    TITLE AS TITLE,
    FORENAME AS CONTACT_FORENAME,
    PERSONALEMAIL AS PERSONAL_EMAIL,
    BUSINESSEMAIL AS BUSINESS_EMAIL,
    TELEPHONE AS TELEPHONE_NUMBER,
    FAX AS FAX,
    EXTENSION AS EXTENSION,
    MOBILE AS MOBILE_NUMBER,
    JOBTITLE AS JOB_TITLE,
    CATEGORY1 AS CATEGORY_1,
    CATEGORY2 AS CATEGORY_2,
    STARTDT AS START_DATE_TIME,
    ENDDT AS END_DATE_TIME,
    `A#112001102` AS FK_DEPARTMENT,
    EMAIL AS EMAIL_ADDRESS,
    NETWORKLOGON AS NETWORK_LOGON,
    PREFNAME AS PREF_NAME,
    MARITALSTATUS AS MARITAL_STATUS_FLAG,
    BIRTHDT AS DATE_OF_BIRTH,
    HOMETEL AS HOME_TELEPHONE_NUMBER,
    CONTACTADDRESS AS CONTACT_ADDRESS,
    RELATIONSHIP AS RELATIONSHIP,
    ADDEDZONE AS ADDED_ZONE,
    UPDATEDZONE AS UPDATED_ZONE,
    INITIALPASSWORD AS INITIAL_PASSWORD,
    RETURNDT AS RETURN_DATE_TIME,
    `A#112001135` AS `A#112001135`,
    ATTACHMENTS AS ATTACHEMENTS,
    VIP AS VIP,
    MAILBOX AS MAILBOX,
    GRAPHIC AS GRAPHIC,
    ASSOCIATION AS ASSOCIATION,
    PREFEREDCONTACT AS PREFEREDCONTACT,
    TWITTERID AS TWITTER_ID,
    CHATTERID AS CHATTER_ID,
    OBJECTGUID AS OBJECTGUID,
    `A#112001237` AS `A#112001237`,
    STAFFID AS STAFF_ID,
    `A#112001243` AS `A#112001243`,
    LINEMANAGER AS LINE_MANAGER,
    DTSXID AS DTSX_ID,
    DISTINGUISHEDNA AS DISTINGUISHEDNA,
    `A#112001244` AS `A#112001244`,
    LINEMANEMAIL AS LINE_MANAGER_EMAIL,
    LINEMANDN AS LINEMANDN,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    MDP_LOAD_DATETIME,
    __START_AT AS ROW_START_DATETIME,
    __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_sunrise_int.contacts
    """)

    # Define the window specification
    windowSpec = dlf.get_window_spec("SERVICEREQNO", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df

# COMMAND ----------

@dlt.table(
    name = "sunrise_department",
    comment = "List of departments at LBS."
)
@dlt.expect("SERVICEREQNO is not null", "SERVICEREQNO IS NOT NULL")
def silver_sunrise_department():
    df = spark.sql(f"""
    SELECT  
    SERVICEREQNO AS SERVICEREQNO,
    SERVICEREQID AS DEPARTMENT_ID,
    NAME AS DEPARTMENT_NAME,
    DESCRIPTION AS DEPARTMENT_DESCRIPTION,
    STATEID AS STATE_ID,
    LIFECYCLEID AS LIFECYCLE_ID,
    ADDEDDATE AS ADDED_DATE_TIME,
    ADDEDBY AS ADDED_BY,
    UPDATEDDATE AS UPDATED_DATE_TIME,
    UPDATEDBY AS UPDATED_BY,
    SYSACCOUNTNAME AS SYS_ACCOUNT_NAME,
    SYSACCOUNTDESC AS SYS_ACCOUNT_DESC,
    EXTERNALACCOUNT AS EXTERNAL_ACCOUNT,
    PASSWORDLASTCHNGD AS PASSWORD_LAST_CHANGED,
    STATUS AS STATUS_FLAG,
    DELETESTATUS AS DELETE_STATUS_FLAG,
    OWNERACCOUNT AS OWNER_ACCOUNT,
    OWNERGROUP AS OWNER_GROUP,
    SITE AS SITE,
    ADDRESS1 AS ADDRESS_1,
    ADDRESS2 AS ADDRESS_2,
    ADDRESS3 AS ADDRESS_3,
    ADDRESS4 AS ADDRESS_4,
    ADDRESS5 AS ADDRESS_5,
    POSTCODE AS POSTCODE,
    SWITCHBOARD AS SWITCH_BOARD,
    FAX AS FAX,
    WEBSITE AS WEBSITE,
    CATEGORY1 AS CATEGORY_1,
    CATEGORY2 AS CATEGORY_2,
    COUNTRY AS COUNTRY,
    `A#112001103` AS `A#112001103`,
    TYPE AS TYPE,
    ADDEDZONE AS ADDED_ZONE,
    UPDATEDZONE AS UPDATED_ZONE,
    ATTACHMENTS AS ATTACHEMENTS,
    `A#112001163` AS `A#112001163`,
    SLAUSAGE AS SLA_USAGE,
    GRAPHIC AS GRAPHIC,
    ASSOCIATION AS ASSOCIATION,
    ISCUSTOMER AS IS_CUSTOMER_FLAG,
    MAP AS MAP,
    LONGITUDE AS LONGITUDE,
    LATITUDE AS LATITUDE,
    `A#112001239` AS `A#112001239`,
    `A#112001242` AS `A#112001242`,
    FLOOR AS FLOOR,
    GENERALMANAGER AS GENERAL_MANAGER,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    MDP_LOAD_DATETIME,
    __START_AT AS ROW_START_DATETIME,
    __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_sunrise_int.departments
    """)

    # Define the window specification
    windowSpec = dlf.get_window_spec("SERVICEREQNO", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df

# COMMAND ----------

@dlt.table(
    name = "sunrise_service",
    comment = "tbc."
)
@dlt.expect("SERVICEREQNO is not null", "SERVICEREQNO IS NOT NULL")
def silver_sunrise_service():
    df = spark.sql(f"""
    SELECT  
    SERVICEREQNO AS SERVICEREQNO,
    SERVICEREQID AS SERVICE_ID,
    NAME AS SERVICE_NAME,
    DESCRIPTION AS SERVICE_DESCRIPTION,
    STATEID AS STATE_ID,
    LIFECYCLEID AS LIFECYCLE_ID,
    ADDEDDATE AS ADDED_DATE_TIME,
    ADDEDBY AS ADDED_BY,
    UPDATEDDATE AS UPDATED_DATE_TIME,
    UPDATEDBY AS UPDATED_BY,
    SYSACCOUNTNAME AS SYS_ACCOUNT_NAME,
    SYSACCOUNTDESC AS SYS_ACCOUNT_DESC,
    SYSPASSWORD AS SYS_PASSWORD,
    EXTERNALACCOUNT AS EXTERNAL_ACCOUNT,
    PASSWORDLASTCHNGD AS PASSWORD_LAST_CHANGED,
    STATUS AS STATUS_FLAG,
    DELETESTATUS AS DELETE_STATUS_FLAG,
    OWNERACCOUNT AS OWNER_ACCOUNT,
    OWNERGROUP AS OWNER_GROUP,
    ADDEDZONE AS ADDED_ZONE,
    UPDATEDZONE AS UPDATED_ZONE,
    ATTACHMENTS AS ATTACHEMENTS,
    `A#112001153` AS `A#112001153`,
    SERVICESTATUS AS SERVICE_STATUS,
    `A#112001157` AS `A#112001157`,
    CRITICALITY AS CRITICALITY,
    `A#112001158` AS `A#112001158`,
    ANNUALCOST AS ANNUAL_COST,
    MONTHLYCOST AS MONTHLY_COST,
    MONTHSERVICECHA AS MONTH_SERVICE_CHARGE,
    ANNUALSERVICECH AS ANNUAL_SERVICE_CHARGE,
    PROJECTEDANNREV AS PROJECTED_ANNUAL_REVENUE,
    `A#112001159` AS `A#112001159`,
    TASKTYPE AS TASK_TYPE,
    TYPE AS TYPE,
    SUBTYPE AS SUB_TYPE,
    ACTIONRETIRESER AS ACTION_RETIRE_SERVICE,
    EXISTINGSERVICE AS EXISTING_SERVICE,
    CURRENCY AS CURRENCY,
    GRAPHIC AS GRAPHIC,
    ASSOCIATION AS ASSOCIATION,
    TASKS AS TASKS,
    ITILSTATE AS ITIL_STATE,
    ENDUSERACCESS AS END_USER_ACCESS,
    SERVICEFEATURES AS SERVICE_FEATURES,
    SERVICEFUNCTION AS SERVICE_FUNCTION,
    SERVICEBENEFITS AS SERVICE_BENEFITS,
    SERVICEDEF AS SERVICE_DEF,
    AVAILABILITYTGT AS AVAILABILITY_TGT,
    COSTPERCREDIT AS COST_PER_CREDIT,
    ESTIMATEDCOST AS ESTIMATED_COST,
    COUNTOFFERINGS AS COUNT_OFFERINGS,
    SERVICEDEFTWO AS SERVICEDEFTWO,
    SERVICEDEFTHREE AS SERVICEDEFTHREE,
    AVAILABLETARGET AS AVAILABLE_TARGET,
    TARGETHOURSLOST AS TARGET_HOURS_LOST,
    SERVICEUNAGRP AS SERVICEUNAGRP,
    PATCHINGGROUP AS PATCHING_GROUP,
    MAINTENANCEWIND AS MAINTENANCE_WIND,
    DRRTO AS DRRTO,
    SERVHOUMOFR AS SERVICE_HOURS_MONDAY_FROM,
    SERVHOUMOTO AS SERVICE_HOURS_MONDAY_TO,
    SERVHOUTUFR AS SERVICE_HOURS_TUESDAY_FROM,
    SERVHOUTUTO AS SERVICE_HOURS_TUESDAY_TO,
    SERVHOUWEFR AS SERVICE_HOURS_WEDNESDAY_FROM,
    SERVHOUWETO AS SERVICE_HOURS_WEDNESDAY_TO,
    SERVHOUTHFR AS SERVICE_HOURS_THURSDAY_FROM,
    SERVHOUTHTO AS SERVICE_HOURS_THURSDAY_TO,
    SERVHOUFRFR AS SERVICE_HOURS_FRIDAY_FROM,
    SERVHOUFRTO AS SERVICE_HOURS_FRIDAY_TO,
    SERVHOUSAFR AS SERVICE_HOURS_SATURDAY_FROM,
    SERVHOUSATO AS SERVICE_HOURS_SATURDAY_TO,
    SERVHOUSUFR AS SERVICE_HOURS_SUNDAY_FROM,
    SERVHOUSUTO AS SERVICE_HOURS_SUNDAY_TO,
    OUTOFHRSESCAVAI AS OUT_OF_HOURS_ESCALATIOM_AVAILABLE,
    SLATYPE AS SLA_TYPE,
    `A#112001252` AS `A#112001252`,
    ARCHITECTURELIN AS ARCHITECTURE_LINK,
    MONITORLINK AS MONITOR_LINK,
    `H#FORENAME0` AS FORENAME,
    `H#112001256` AS `H#112001256`,
    `H#NAME0` AS SURNAME,
    `H#FORENAME1` AS FORENAME_1,
    `H#112001257` AS `H#112001257`,
    `H#NAME1` AS CONTACT_DEPARTMENT_NAME,
    `H#APPLICATIONNAME0` AS APPLICATION_NAME,
    `H#112001276` AS `H#112001276`,
    `H#DESCRIPTION0` AS KNOWLEDGE_SYMPTOMS,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    MDP_LOAD_DATETIME
    FROM {env_var}_catalog.bronze_sunrise_int.service
    """)

    # Define the window specification
    windowSpec = dlf.get_window_spec("SERVICEREQNO", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df

# COMMAND ----------

@dlt.table(
    name = "sunrise_map",
    comment = "tbc."
)
@dlt.expect("Name is not null", "Name IS NOT NULL")
def silver_itsm_map():
    df = spark.sql(f"""
    SELECT  
    Name,
    ServiceID AS SERVICE_ID,
    CATEGORY1 AS CATEGORY_1,
    CATEGORY2 AS CATEGORY_2,
    CATEGORY3 AS CATEGORY_3,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID
    FROM {env_var}_catalog.bronze_sunrise_int.serviceid
    """)

    return df

# COMMAND ----------

@dlt.table(
    name = "sunrise_incident_history",
    comment = "Sunrise Incidents History Table used in fact measures"
)
@dlt.expect("SERVICEREQNO is not null", "SERVICEREQNO IS NOT NULL")
def silver_sunrise_incidents_history():
    df = spark.sql(f"""
    SELECT  
    SERVICEREQNO AS SERVICEREQNO,
    SERVREQHISTORYNO AS INCIDENT_HISTORY_NO,
    CLOSETYPE AS CLOSE_TYPE,
    ACTIONDETAILS AS ACTION_DETAILS,
    RESOLVETYPE AS RESOLVE_TYPE,
    OPERATIONID AS OPERATION_ID,
    PREVSTATEID AS PREVIOUS_STATE_ID,
    STATEID AS STATE_ID,
    ADDEDDATE AS ADDED_DATE_TIME,
    ADDEDBY AS ADDED_BY,
    OWNERACCOUNT AS OWNER_ACCOUNT,
    OWNERGROUP AS OWNER_GROUP,
    UPDATEDDATE AS UPDATED_DATE_TIME,
    UPDATEDBY AS UPDATED_BY,
    INTACTIONTYPE AS INT_ACTION_TYPE,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    MDP_LOAD_DATETIME,
    __START_AT AS ROW_START_DATETIME,
    __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_sunrise_int.incidents_h
    """)

    # Define the window specification
    windowSpec = dlf.get_window_spec("SERVICEREQNO", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df
