SELECT
  CAST(UPPER(cc.cc_id) AS STRING) AS COMPANY_CATEGORIES_ID,
  CAST(UPPER(cc.com_id) AS STRING) AS COMPANY_ID,
  CAST(UPPER(cc.cat_id) AS STRING) AS CATEGORY_ID,
  CAST(UPPER(cc.aa_id) AS STRING) AS AUDIT_ARTICLES_ID,
  CAST(cc.version AS INT) AS COMPANY_CATEGORIES_VERSION,
  CAST(cc.migrationCode AS BINARY) AS MIGRATION_CODE,
  CAST(cc.isDeleted AS TINYINT) AS IS_DELETED,
  CAST(cc.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(cc.MDP_LOAD_ID AS INT) AS MDP_LOAD_ID,
  CAST(cc.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(cc.MDP_LOAD_TYPE AS STRING) AS MDP_LOAD_TYPE
FROM {env_var}_catalog.bronze_spectra_int.companycategories cc