SELECT
  CAST(UPPER(c.CAT_ID) AS STRING) AS CATEGORIES_ID,
  CAST(c.CAT_TID AS BIGINT) AS CATEGORIES_TID,
  CAST(UPPER(c.CAG_ID) AS STRING) AS CATEGORY_GROUPS_ID,
  CAST(UPPER(c.AA_ID) AS STRING) AS AUDIT_ARTICLES_ID,
  CAST(UPPER(c.NAME) AS STRING) AS CATEGORIES_NAME,
  CAST(c.VERSION AS INT) AS CATGEORIES_VERSION,
  CAST(c.ISDELETED AS TINYINT) AS IS_DELETED,
  CAST(c.ISCATEGORISATIONONLY AS TINYINT) AS IS_CATEGORISATION_ONLY,
  CAST(c.MIGRATIONCODE AS BINARY) AS MIGRATION_CODE,
  CAST(c.PREVENTMANUALRECATEGORISATION AS TINYINT) AS PREVENT_MANUAL_RECATEGORISATION,
  CAST(c.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(c.MDP_LOAD_ID AS INT) AS MDP_LOAD_ID,
  CAST(c.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(c.MDP_LOAD_TYPE AS STRING) AS MDP_LOAD_TYPE
FROM {env_var}_catalog.bronze_spectra_int.categories c