SELECT
  CAST(wit.WIT_ID AS BIGINT) AS WORK_ITEM_TYPE_ID,
  CAST(wit.NAME AS STRING) AS WORK_ITEM_NAME,
  CAST(wit.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(wit.MDP_LOAD_ID AS INT) AS MDP_LOAD_ID,
  CAST(wit.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(wit.MDP_LOAD_TYPE AS STRING) AS MDP_LOAD_TYPE
FROM {env_var}_catalog.bronze_spectra_int.workitemtypes wit