SELECT
  CAST(wde.de_id AS BIGINT) AS DATA_ENTITY_ID,
  CAST(wde.archiveIndicator AS INT) AS ARCHIVE_INDICATOR,
  CAST(wde.wi_id AS BIGINT) AS WORK_ITEM_ID,
  CAST(wde.nde_tid AS INT) AS DATA_ELEMENT_ID,
  CAST(wde.strValue AS STRING) AS STR_VALUE,
  CAST(wde.decValue AS DECIMAL(24,4)) AS DECIMAL_VALUE,
  CAST(wde.encryptedValue AS BINARY) AS ENCRYPTED_VALUE,
  CAST(wde.a_tid AS BIGINT) AS ATTRIBUTE_TID,
  CAST(wde.confidence AS DOUBLE) AS CONFIDENCE,
  CAST(wde.changeTime AS TIMESTAMP) AS CHANGE_TIME,
  CAST(wde.isRequiresComponentExtraction AS BOOLEAN) AS IS_REQUIRES_COMPONENT_EXTRACTION,
  CAST(wde.isIndexed AS BOOLEAN) AS IS_INDEXED,
  CAST(wde.isValidated AS BOOLEAN) AS IS_VALIDATED,
  CAST(wde.isPreferred AS BOOLEAN) AS IS_PREFERRED,
  CAST(wde.MDP_LOAD_ID AS INT) AS MDP_LOAD_ID,
  CAST(wde.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(wde.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(wde.MDP_LOAD_TYPE AS STRING) AS MDP_LOAD_TYPE,
  CAST(wde.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(wde.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_spectra_int.workitemdataentities wde
WHERE wde.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1