SELECT
  CAST(UPPER(c.com_id) AS STRING) AS COMPANIES_ID,
  CAST(c.com_tid AS BIGINT) AS COMPANIES_TID,
  CAST(UPPER(c.aa_id) AS STRING) AS AUDIT_ARTICLES_ID,
  CAST(UPPER(c.cog_id) AS STRING) AS COMPANY_GROUPS_ID,
  CAST(UPPER(c.cal_id) AS STRING) AS CALENDARS_ID,
  CAST(c.name AS STRING) AS COMPANIES_NAME,
  CAST(c.version AS INT) as COMPANIES_VERSION,
  CAST(c.migrationCode AS BINARY) AS MIGRATION_CODE,
  CAST(c.preventManualRecategorisation AS INT) AS PREVENT_MANUAL_RECATEGORISATION,
  CAST(c.isDeleted AS tinyint) AS IS_DELETED,
  CAST(c.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(c.MDP_LOAD_ID AS INT) AS MDP_LOAD_ID,
  CAST(c.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(c.MDP_LOAD_TYPE AS STRING) AS MDP_LOAD_TYPE
FROM {env_var}_catalog.bronze_spectra_int.companies c