# Databricks notebook source
import dlt
from pyspark.sql.functions import row_number, col, expr
from pyspark.sql.window import Window
import mdp_databricks_common.silver_layer_functions as dlf

env_var = dbutils.secrets.get(scope = 'data-kv-scope', key = 'data-platform-environment')

# COMMAND ----------

@dlt.table(
    name = "enquire_complaint",
    comment = "details relating to the complaint that has been made"
)
@dlt.expect("COMPLAINT_ID is not null", "COMPLAINT_ID IS NOT NULL")
def silver_enquire_complaint():

    df = spark.sql(f"""
    SELECT
    CAST(COMPLAINT_ID AS BIGINT) AS COMPLAINT_ID,
    COMPLAINT_REF AS COMPLAINT_REFERENCE,
    CAST(COMPLAINT_STATUS AS BIGINT) AS COMPLAINT_STATUS,
    CAST(COMPLAINT_TYPE AS BIGINT) AS COMPLAINT_TYPE,
    COMPLAINANT_NAME AS COMPLAINANT_NAME,
    CAST(BA_COMP_LOGGED_AT AS BIGINT) AS BUSINESS_AREA_COMPLAINT_LOGGED_AT,
    LBS_CUSTOMER_IND AS LBS_CUSTOMER_INDICATOR,
    CAST(PERS_COMPL_REF AS BIGINT)  AS PERSON_COMPLAINT_REFERRED_TO,
    INVESTIGATION_NOTES AS INVESTIGATION_NOTES,
    COMPLAINT_ACTION_TAKEN AS COMPLAINT_ACTION_TAKEN,
    CAST(ROOT_CAUSE AS BIGINT) AS ROOT_CAUSE,
    CAST(JUSTIFIED AS BIGINT) AS JUSTIFIED,
    FSA_IND AS FSA_INDICATOR,
    CAST(FSA_REPORTING_CAT AS BIGINT) AS FSA_REPORTING_CATEGORY,
    CAST(FSA_PRODUCT_TYPE AS BIGINT) AS FSA_PRODUCT_TYPE,
    CAST(FSA_ACT_PRODUCT_TYPE AS BIGINT) AS FSA_ACTUAL_PRODUCT_TYPE,
    CAST(FSA_NON_REPORT AS BIGINT) AS FSA_NON_REPORT,
    FOS_IND AS FOS_INDICATOR,
    CAST(FOS_RESOLUTION AS BIGINT) AS FOS_RESOLUTION,
    FOS_OVERTURNED_IND AS FOS_OVERTURNED_INDICATOR,
    CAST(THIRD_PARTY_ID AS BIGINT) AS THIRD_PARTY_ID,
    CUST_SATISFACT_SURV_IND AS CUSTOMER_SATISFACTION_SURVEY_INDICATOR,
    PSR_IND AS PSR_INDICATOR,
    CAST(HR24_HOW_RESOLVED_CODE AS BIGINT) AS 24HR_COMPLAINT_HOW_RESOLVED_CODE,
    CREATED_BY AS CREATED_BY,
    CREATED_DATE AS CREATED_DATE,
    LAST_CHANGED_BY AS LAST_CHANGED_BY,
    LAST_CHANGED_DATE AS LAST_CHANGED_DATE,
    CAST(FOS_CATEGORY AS BIGINT) AS FOS_CATEGORY,
    COMPLAINT_REASON AS COMPLAINT_REASON,
    FOS_OVERTURNED_COMPL_IND AS FOS_OVERTURNED_COMPLAINT_INDICATOR,
    STAFF_MEMBER_COMPL_AGAINST AS STAFF_MEMBER_COMPLAINT_AGAINST,
    CAST(STAFF_MEMBER_COMPL_AGA_ROLE AS BIGINT) AS STAFF_MEMBER_COMPLAINT_AGAINST_ROLE,
    CAST(REASON_FOR_FURTHER_COMPLAINT AS BIGINT) AS REASON_FOR_FURTHER_COMPLAINT,
    CAST(FSA_REPORTING_SUB_CAT AS BIGINT) AS FSA_REPORTING_SUB_CATEGORY,
    CAST(STD_COMPLAINANT_TYPE_ID AS BIGINT) AS COMPLAINANT_TYPE_ID,
    CAST(STD_COMPLNANT_TYPE_BEH_ID AS BIGINT) AS THIRD_PARTY_COMPLAINANT_TYPE_ID,
    CUSTOMER_ACCEPTED_RESOLUTION AS CUSTOMER_ACCEPTED_RESOLUTION,
    AFT_REOPEN_HAS_RES_CHANGED AS AFTER_REOPEN_HAS_RESOLUTION_CHANGED,
    CAST(PREFERRED_METHOD_OF_CONTACT AS BIGINT) AS PREFERRED_METHOD_OF_CONTACT,
    PERS_RESP_TO_COMPLAINT AS PERSON_RESPONDING_TO_COMPLAINT,
    CLAIMS_RELATED AS CLAIMS_RELATED_INDICATOR,
    ROOT_CAUSE_EXTRA_INFO AS ROOT_CAUSE_EXTRA_INFO,
    CAST(REASON_FOR_COMPLAINT_OPT1 AS BIGINT) AS REASON_FOR_COMPLAINT_OPTION_1,
    CAST(REASON_FOR_COMPLAINT_OPT2 AS BIGINT) AS REASON_FOR_COMPLAINT_OPTION_2,
    CAST(REASON_FOR_COMPLAINT_OPT3 AS BIGINT) AS REASON_FOR_COMPLAINT_OPTION_3,
    FOS_REFERENCE_NUMBER AS FOS_REFERENCE_NUMBER,
    FOS_SUBMISSION_ASSIGN AS FOS_SUBMISSION_ASSIGNED_TO,
    FOS_POTENTIAL_IMPROVEMENTS AS FOS_POTENTIAL_IMPROVEMENTS,
    CAST(FOS_OUTCOME_CATEGORY AS BIGINT) AS FOS_OUTCOME_CATEGORY,
    CLT_ASSIGNEE AS CLT_ASSIGNEE,
    COMPLAINT_OR_FEEDBACK AS COMPLAINT_OR_FEEDBACK_INDICATOR,
    CAST(STD_COMPLT_RECEIVED_METH_ID AS BIGINT) AS COMPLAINT_RECEIVED_METHOD_ID,
    PLEVIN_COMPLAINT AS PLEVIN_COMPLAINT_INDICATOR,
    COLD_ACCOUNT_NUMBER_YN AS COLD_ACCOUNT_NUMBER_INDICATOR,
    COLD_ACCOUNT_NUMBER AS COLD_ACCOUNT_NUMBER,
    CAST(STD_NHCNSC_LET_REQ_ID AS BIGINT) AS NHCNSC_LETTER_REQUIRED_ID,
    CAST(STD_PAYM_SERV_TYPE_ID AS BIGINT) AS PAYMENT_SERVICE_TYPE_ID,
    PAYM_SERV_TYPE_OTH AS PAYMENT_SERVICE_TYPE_OTHER,
    PAYMENT_SERVICES_RELATED AS PAYMENT_SERVICES_RELATED_INDICATOR,
    CAST(STD_RC_AREA_ID AS BIGINT) AS ROOT_CAUSE_AREA_ID,
    CAST(STD_RC_JOURNEY_ID AS BIGINT) AS ROOT_CAUSE_JOURNEY_ID,
    CAST(STD_RC_CHANNEL_ID AS BIGINT) AS ROOT_CAUSE_CHANNEL_ID,
    CAST(STD_RC_ANALYSIS_ID AS BIGINT) AS ROOT_CAUSE_ANALYSIS_ID,
    CAST(STD_RC_ANALYSIS_CAT_ID AS BIGINT) AS ROOT_CAUSE_ANALYSIS_CATEGORY_ID,
    CAST(STD_CONS_DUTY_OUTC_ID AS BIGINT) AS CONSUMER_DUTY_OUTCOME_ID,
    CAST(STD_CONS_DUTY_SUBO_ID AS BIGINT) AS CONSUMER_DUTY_SUB_OUTCOME_ID,
    IT_INCIDENT_REFERENCE AS IT_INCIDENT_REFERENCE,
    RISK_INCIDENT_REFERENCE AS RISK_INCIDENT_REFERENCE,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    CAST(MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
    __START_AT AS ROW_START_DATETIME,
    __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_enquire_con.complaint
""")

    # Define the window specification
    windowSpec = dlf.get_window_spec("COMPLAINT_ID", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df

# COMMAND ----------

@dlt.table(
    name="enquire_complaint_referred_to",
    comment="who the complaint has been referred to"
)
@dlt.expect("COMPLAINT_REFERRED_TO_ID is not null", "COMPLAINT_REFERRED_TO_ID IS NOT NULL")
def silver_enquire_std_complaint_ref_to():
    df = spark.sql(f"""
    SELECT 
    CAST(STD_COMPLAINT_REF_TO_ID AS BIGINT) AS COMPLAINT_REFERRED_TO_ID,
    LBS_USER_ID AS LBS_USER_ID,
    FULL_NAME,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    CAST(MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
    __START_AT AS ROW_START_DATETIME,
    __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_enquire_con.std_complaint_ref_to
    """)

    # Define the window specification
    windowSpec = dlf.get_window_spec("COMPLAINT_REFERRED_TO_ID", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df

# COMMAND ----------

@dlt.table(
    name = "enquire_complaint_third_party",
    comment = "third parties that are linked to the complaint i.e. legal & general, barclays, aviva etc."
)
@dlt.expect("THIRD_PARTY_ID is not null", "THIRD_PARTY_ID IS NOT NULL")
def silver_enquire_std_third_party():

    df = spark.sql(f"""
    SELECT 
    CAST(STD_THIRD_PARTY_ID AS BIGINT) AS THIRD_PARTY_ID,
    DESCRIPTION AS THRID_PARTY_DESCRIPTION,
    CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
    CAST(MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
    __START_AT AS ROW_START_DATETIME,
    __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_enquire_con.std_third_party
""")

    # Define the window specification
    windowSpec = dlf.get_window_spec("THIRD_PARTY_ID", "MDP_LOAD_DATETIME")

    # Add the CURRENT_FLAG column
    df = dlf.get_row_number(df, windowSpec)

    return df
