SELECT
	CAST(UPPER(vr.ValuationReportId) AS STRING) AS VALUATION_REPORT_ID,
	CAST(UPPER(vr.CaseId) AS STRING) AS CASE_ID,
	CAST(vr.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
	CAST(vr.ExpiryDate AS TIMESTAMP) AS EXPIRY_DATETIME,
	CAST(vr.ReportDate AS TIMESTAMP) AS REPORT_DATETIME,
	CAST(vr.InspectionDate AS TIMESTAMP) AS INSPECTION_DATETIME,
	CAST(vr.ReportType AS STRING) AS REPORT_TYPE,
	CAST(vr.ValuationStatus AS STRING) AS VALUATION_STATUS,
	CAST(vr.UpgradedValuationReason AS STRING) AS UPGRADED_VALUATION_REASON,
	CAST(vr.RevisionNumber AS INT) AS REVISION_NUMBER,
	CAST(vr.ValuationAmount AS DECIMAL(10,2)) AS VALUATION_AMOUNT,
	CAST(vr.CustomerShare AS DECIMAL(10,2)) AS CUSTOMER_SHARE,
	CAST(vr.IsTranscription AS TINYINT) AS IS_TRANSCRIPTION,
	CAST(vr.UpgradeToInternalInspectionRequired AS TINYINT) AS IS_INTERNAL_INSPECTION_REQUIRED,
	CAST(vr.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
	CAST(vr.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
	CAST(vr.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
	CAST(vr.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
	CAST(vr.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_int.valuation_report vr
WHERE vr.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1;