SELECT
  CAST(UPPER(sp.ProductId) AS STRING) AS PRODUCT_ID,
  CAST(UPPER(sp.CaseId) AS STRING) AS CASE_ID,
  CAST(sp.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(sp.ProductCode AS INT) AS PRODUCT_CODE,
  CAST(sp.ProductDescription AS STRING) AS PRODUCT_DESCRIPTION,
  CAST(sp.ProductType AS STRING) AS PRODUCT_TYPE,
  CAST(sp.BeneficialRatePeriod AS STRING) AS BENEFICIAL_RATE_PERIOD,
  CAST(sp.AccountRegulation AS STRING) AS ACCOUNT_REGULATION,
  CAST(sp.TermInMonths AS INT) AS TERM_IN_MONTHS,
  CAST(sp.CapitalAmount AS DECIMAL(10, 2)) AS CAPITAL_AMOUNT,
  CAST(sp.InterestOnlyAmount AS DECIMAL(10, 2)) AS INTEREST_ONLY_AMOUNT,
  CAST(sp.InitialMonthlyRepayment AS DECIMAL(8, 2)) AS INITIAL_MONTHLY_REPAYMENT,
  CAST(sp.InitialInterestRate AS DECIMAL(10, 3)) AS INITIAL_INTEREST_RATE,
  CAST(sp.Apr AS DECIMAL(10, 3)) AS APR,
  CAST(sp.MaximumLTV AS DECIMAL(10, 3)) AS MAXIMUM_LTV,
  CAST(sp.ForDebtConsolidation AS TINYINT) AS IS_FOR_DEBT_CONSILIDATION,
  CAST(sp.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH, 
  CAST(sp.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(sp.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(sp.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(sp.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_int.selected_product sp
WHERE sp.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1
