SELECT
  CAST(UPPER(rs.LoanRequirementId) AS STRING) AS LOAN_REQUIREMENT_ID,
  CAST(rs.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(rs.StrategyType AS STRING) AS STRATEGY_TYPE,
  CAST(rs.Amount AS DECIMAL(10, 2)) AS AMOUNT,
  CAST(rs.CurrentValue AS DECIMAL(10, 2)) AS CURRENT_VALUE,
  CAST(rs.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(rs.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(rs.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
  CAST(rs.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(rs.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_int.repayment_strategy rs
WHERE rs.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1