SELECT
	CAST(UPPER(avm.AutomatedValuationModelId) AS STRING) AS AUTOMATED_VALUATION_MODEL_ID,
	CAST(UPPER(avm.CaseId) AS STRING) AS CASE_ID,
	CAST(avm.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
	CAST(avm.ExpiryDate AS TIMESTAMP) AS EXPIRY_DATETIME,
	CAST(avm.ReportDate AS TIMESTAMP) AS REPORT_DATETIME,
	CAST(avm.RequestedValuationEffectiveDate AS TIMESTAMP) AS REQUESTED_VALUATION_EFFECTIVE_DATETIME,
	CAST(avm.Status AS STRING) AS STATUS,
	CAST(avm.AvmProviderReference AS INT) AS AVM_PROVIDER_REFERENCE,
	CAST(avm.LenderReference AS INT) AS LENDER_REFERENCE,
	CAST(avm.ConfidenceLevel AS DECIMAL(10,4)) AS CONFIDENCE_LEVEL,
	CAST(avm.ValuationAmount AS DECIMAL(19,2)) AS VALUATION_AMOUNT,
	CAST(avm.ReinstatementCost AS DECIMAL(19,2)) AS REINSTATEMENT_COST,
	CAST(avm.AssessedRentalMonthlyAmount AS DECIMAL(10,2)) AS ASSESSED_RENTAL_MONTHLY_AMOUNT,
	CAST(avm.MarketRentalMonthlyAmount AS DECIMAL(10,2)) AS MARKET_RENTAL_MONTHLY_AMOUNT,
	CAST(avm.IsSuccessful AS TINYINT) AS IS_SUCCESSFUL,
	CAST(avm.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
	CAST(avm.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
	CAST(avm.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
	CAST(avm.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
	CAST(avm.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_int.automated_valuation_model avm
WHERE avm.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1;