SELECT
	CAST(UPPER(r.RemittanceId) AS STRING) AS REMITTANCE_ID,
	CAST(UPPER(r.CaseId) AS STRING) AS CASE_ID,
	CAST(r.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
	CAST(r.CompletionDate AS TIMESTAMP) AS COMPLETION_DATETIME,
	CAST(r.EffectiveDate AS TIMESTAMP) AS EFFECTIVE_DATETIME,
	-- Using "REMITTANCE_TYPE" instead of "TYPE" because "TYPE" is a reserved keyword
	CAST(r.Type AS STRING) AS REMITTANCE_TYPE,
	CAST(r.RemittanceStatus AS STRING) AS REMITTANCE_STATUS,
	CAST(r.Reference AS STRING) AS REFERENCE,
	CAST(r.Amount AS DECIMAL(10,2)) AS AMOUNT,
	CAST(r.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
	CAST(r.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
	CAST(r.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATETIME,
	CAST(r.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
	CAST(r.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_int.remittance r
WHERE r.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1;