SELECT
  CAST(UPPER(ovc.OfferId) AS STRING) AS OFFER_ID,
  CAST(ovc.LastUpdatedDate AS TIMESTAMP) AS LAST_UPDATED_DATETIME,
  CAST(ovc.VersionNumber AS SMALLINT) AS VERSION_NUMBER,
  CAST(ovc.Reference AS STRING) AS REFERENCE,
  CAST(ovc.Description AS STRING) AS DESCRIPTION,
  CAST(ovc.Waived AS TINYINT) AS WAIVED,
  CAST(ovc.MDP_ROW_HASH AS STRING) AS MDP_ROW_HASH,
  CAST(ovc.MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
  CAST(ovc.MDP_LOAD_DATETIME AS TIMESTAMP) AS MDP_LOAD_DATEIME,
  CAST(ovc.__START_AT AS TIMESTAMP) AS ROW_START_DATETIME,
  CAST(ovc.__END_AT AS TIMESTAMP) AS ROW_END_DATETIME
FROM {env_var}_catalog.bronze_mso_int.offer_version_condition ovc
WHERE ovc.__END_AT IS NULL -- Equivalent of ROW_IS_CURRENT = 1