# Databricks notebook source
import dlt
from pyspark.sql.functions import row_number, col, expr
from pyspark.sql.window import Window

import mdp_databricks_common.silver_layer_functions as dlf
from mdp_databricks_common.feature_toggle import feature_toggle as ft

env_var = dbutils.secrets.get(scope = 'data-kv-scope', key = 'data-platform-environment')

# COMMAND ----------

# MAGIC %md
# MAGIC ----------------------------------------------------------------------
# MAGIC # Mambu Transition-State-1 (Baseline Savings -- deployed to Production in December 2024)

# COMMAND ----------

@dlt.table(
    name="mambu_saving_account", 
    comment="A savings account representing either a daily account, a term-deposit or a checking account which is essentially the current account of the client where deposits and withdrawals can be made."
)
@dlt.expect("Check that ENCODED_KEY is not null", "ENCODED_KEY IS NOT NULL")
def mambu_saving_account():

    df = spark.sql(
        f"""
        SELECT              
            ENCODEDKEY AS ENCODED_KEY,
            ACCOUNTHOLDERKEY AS ACCOUNT_HOLDER_KEY,
            ACCOUNTHOLDERTYPE AS ACCOUNT_HOLDER_TYPE,
            PRODUCTTYPEKEY AS PRODUCT_TYPE_KEY,
            ASSIGNEDBRANCHKEY AS ASSIGNED_BRANCH_KEY,
            ASSIGNEDUSERKEY AS ASSIGNED_USER_KEY,
            ASSIGNEDCENTREKEY AS ASSIGNED_CENTRE_KEY,
            INTERESTSETTINGSKEY AS INTEREST_SETTINGS_KEY,
            OVERDRAFTINTERESTSETTINGSKEY AS OVERDRAFT_INTEREST_SETTINGS_KEY,
            LINEOFCREDITKEY AS LINE_OF_CREDIT_KEY,
            WITHHOLDINGTAXSOURCEKEY AS WITHHOLDING_TAX_SOURCE_KEY,
            ID,
            ACCOUNTSTATE AS ACCOUNT_STATE,
            ACCOUNTTYPE AS ACCOUNT_TYPE,
           (CASE WHEN BALANCE = '0E-18' OR BALANCE = 0 THEN 0.0
                 ELSE CAST(BALANCE AS DECIMAL(18,2)) END) AS BALANCE,
           (CASE WHEN ACCRUEDINTEREST = '0E-18' OR ACCRUEDINTEREST = 0 THEN 0.0
                 ELSE CAST(ACCRUEDINTEREST AS DECIMAL(18,2)) END) AS ACCRUED_INTEREST,
           (CASE WHEN OVERDRAFTINTERESTACCRUED = '0E-18' OR OVERDRAFTINTERESTACCRUED = 0 THEN 0.0
                 ELSE CAST(OVERDRAFTINTERESTACCRUED AS DECIMAL(18,2)) END) AS OVERDRAFT_INTEREST_ACCRUED,
            CAST(CLOSEDDATE AS DATE) AS CLOSED_DATE,
            CLOSEDDATE AS CLOSED_DATETIME,
            CAST(APPROVEDDATE AS DATE) AS APPROVED_DATE,
            APPROVEDDATE AS APPROVED_DATETIME,
            CAST(ACTIVATIONDATE AS DATE) AS ACTIVATION_DATE,
            ACTIVATIONDATE AS ACTIVATION_DATETIME,
            CAST(LASTINTERESTCALCULATIONDATE AS DATE) AS LAST_INTEREST_CALCULATION_DATE,
            LASTINTERESTCALCULATIONDATE AS LAST_INTEREST_CALCULATION_DATETIME,
            CAST(LASTINTERESTSTOREDDATE AS DATE) AS LAST_INTEREST_STORED_DATE,
            LASTINTERESTSTOREDDATE AS LAST_INTEREST_STORED_DATETIME,
            CAST(CREATIONDATE AS DATE) AS CREATION_DATE,
            CREATIONDATE AS CREATION_DATETIME,
            CAST(LASTACCOUNTAPPRAISALDATE AS DATE) AS LAST_ACCOUNT_APPRAISAL_DATE,
            LASTACCOUNTAPPRAISALDATE AS LAST_ACCOUNT_APPRAISAL_DATETIME,
            MATURITYDATE AS MATURITY_DATE,
            MAXWIDTHDRAWLAMOUNT AS MAX_WITHDRAWL_AMOUNT,
            NAME,
            RECOMMENDEDDEPOSITAMOUNT AS RECOMMENDED_DEPOSIT_AMOUNT,
            TARGETAMOUNT AS TARGET_AMOUNT,
            OVERDRAFTAMOUNT AS OVERDRAFT_AMOUNT,
            INTERESTDUE AS INTEREST_DUE,
            FEESDUE AS FEES_DUE,
            OVERDRAFTLIMIT AS OVERDRAFT_LIMIT,
            OVERDRAFTEXPIRYDATE AS OVERDRAFT_EXPIRY_DATE,
            ALLOWOVERDRAFT AS ALLOW_OVERDRAFT,
           (CASE WHEN LOCKEDBALANCE = '0E-18' OR LOCKEDBALANCE = 0 THEN 0.0
                 ELSE CAST(LOCKEDBALANCE AS DECIMAL(18,2)) END) AS LOCKED_BALANCE,
            INTERESTPAYMENTPOINT AS INTEREST_PAYMENT_POINT,
            INTERESTPAYMENTDATES AS INTEREST_PAYMENT_DATES,
            LASTOVERDRAFTINTERESTREVIEWDATE AS LAST_OVERDRAFT_INTEREST_REVIEW_DATE,
            LOCKEDDATE AS LOCKED_DATE,
            CURRENCYCODE AS CURRENCY_CODE,
            LASTSETTOARREARSDATE AS LAST_SET_TO_ARREARS_DATE,
           (CASE WHEN HOLDBALANCE = '0E-18' OR HOLDBALANCE = 0 THEN 0.0
                 ELSE CAST(HOLDBALANCE AS DECIMAL(18,2)) END) AS HOLD_BALANCE,
            TECHNICALOVERDRAFTAMOUNT AS TECHNICAL_OVERDRAFT_AMOUNT,
            TECHNICALOVERDRAFTINTERESTACCRUED AS TECHNICAL_OVERDRAFT_INTEREST_ACCRUED,
            TECHNICALINTERESTDUE AS TECHNICAL_INTEREST_DUE,
           (CASE WHEN BLOCKEDBALANCE = '0E-18' OR BLOCKEDBALANCE = 0 THEN 0.0
                 ELSE CAST(BLOCKEDBALANCE AS DECIMAL(18,2)) END) AS BLOCKED_BALANCE,
           (CASE WHEN FORWARDAVAILABLEBALANCE = '0E-18' OR FORWARDAVAILABLEBALANCE = 0 THEN 0.0
                 ELSE CAST(FORWARDAVAILABLEBALANCE AS DECIMAL(18,2)) END) AS FORWARD_AVAILABLE_BALANCE,
           (CASE WHEN MAXDEPOSITBALANCE = '0E-18' OR MAXDEPOSITBALANCE = 0 THEN 0.0
                 ELSE CAST(MAXDEPOSITBALANCE AS DECIMAL(18,2)) END) AS MAX_DEPOSIT_BALANCE,
            NEGATIVEINTERESTACCRUED AS NEGATIVE_INTEREST_ACCRUED,
            LASTINTERESTREVIEWDATE AS LAST_INTEREST_REVIEW_DATE,
            MIGRATIONEVENTKEY AS MIGRATION_EVENT_KEY,
            NOTES,
            CAST(LASTMODIFIEDDATE AS DATE) AS LAST_MODIFIED_DATE,
            CAST(LASTMODIFIEDDATE AS TIMESTAMP) AS LAST_MODIFIED_DATETIME, 
            CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
            TO_TIMESTAMP(MDP_LOAD_DATETIME, 'dd-MMM-yy HH:mm:ss') AS MDP_LOAD_DATETIME,
            __START_AT AS ROW_START_DATETIME,
            __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_mambu_int.savingsaccount 
    """
    )
    
    # Define the window specification
    windowSpec = dlf.get_window_spec("ENCODED_KEY","MDP_LOAD_DATETIME")
    df = dlf.get_row_number(df, windowSpec)   
    return df

# COMMAND ----------

@dlt.table(
    name="mambu_saving_product", 
    comment="Stores templates that specify some predefined information and constraints that are then applied to the savings accounts, associated with a specific savings product. Products can be defined for individuals and groups and has a specified interest rate and the interest calculation frequency."
)
@dlt.expect("Check that ENCODED_KEY is not null", "ENCODED_KEY IS NOT NULL")
def mambu_saving_product():

    df = spark.sql(
        f"""
    SELECT
        ENCODEDKEY AS ENCODED_KEY,
        INTERESTRATESETTINGSKEY AS INTEREST_RATE_SETTINGS_KEY,
        ID,
        ACTIVATED,
        NAME,
        PRODUCTTYPE AS PRODUCT_TYPE,
        CATEGORY,
        DESCRIPTION,
        CAST(FORGROUPS AS TINYINT) AS FOR_GROUPS,
        CAST(FORINDIVIDUALS AS TINYINT) AS FOR_INDIVIDUALS,
        CAST(FORALLBRANCHES AS TINYINT) AS FOR_ALL_BRANCHES,
        CAST(CREATIONDATE AS DATE) AS CREATION_DATE,
        CREATIONDATE AS CREATION_DATETIME,
        CAST(LASTMODIFIEDDATE AS DATE) AS LAST_MODIFIED_DATE,
        CAST(LASTMODIFIEDDATE AS TIMESTAMP) AS LAST_MODIFIED_DATETIME,
        COLLECTINTERESTWHENLOCKED AS COLLECT_INTEREST_WHEN_LOCKED,
        DEFAULTMATURITYPERIOD AS DEFAULT_MATURITY_PERIOD,
       (CASE WHEN DEFAULTOPENINGBALANCE = '0E-18' OR DEFAULTOPENINGBALANCE = 0 THEN 0.0
             ELSE CAST(DEFAULTOPENINGBALANCE AS DECIMAL(18,2)) END) AS DEFAULT_OPENING_BALANCE,
       (CASE WHEN INTERESTCALCULATIONBALANCE = '0E-18' OR INTERESTCALCULATIONBALANCE = 0 THEN 0.0
             ELSE CAST(INTERESTCALCULATIONBALANCE AS DECIMAL(18,2)) END) AS INTEREST_CALCULATION_BALANCE,
        INTERESTPAYMENTPOINT AS INTEREST_PAYMENT_POINT,
        INTERESTPAYMENTDATES AS INTEREST_PAYMENT_DATES,
        INTERESTPAIDINTOACCOUNT AS INTEREST_PAID_INTO_ACCOUNT,
        MATURITYPERIODUNIT AS MATURITY_PERIOD_UNIT,
        MAXMATURITYPERIOD AS MAX_MATURITY_PERIOD,
       (CASE WHEN MAXOPENINGBALANCE = '0E-18' OR MAXOPENINGBALANCE = 0 THEN 0.0
             ELSE CAST(MAXOPENINGBALANCE AS DECIMAL(18,2)) END) AS MAX_OPENING_BALANCE,
        MAXWIDTHDRAWLAMOUNT AS MAX_WITHDRAWL_AMOUNT,
        MINMATURITYPERIOD AS MIN_MATURITY_PERIOD,
       (CASE WHEN MINOPENINGBALANCE = '0E-18' OR MINOPENINGBALANCE = 0 THEN 0.0
             ELSE CAST(MINOPENINGBALANCE AS DECIMAL(18,2)) END) AS MIN_OPENING_BALANCE,
        RECOMMENDEDDEPOSITAMOUNT AS RECOMMENDED_DEPOSIT_AMOUNT,
        MINOVERDRAFTINTERESTRATE AS MIN_OVERDRAFT_INTEREST_RATE,
        MAXOVERDRAFTINTERESTRATE AS MAX_OVERDRAFT_INTEREST_RATE,
        MAXOVERDRAFTLIMIT AS MAX_OVERDRAFT_LIMIT,
        ALLOWOVERDRAFT AS ALLOW_OVERDRAFT,
        ALLOWARBITRARYFEES AS ALLOW_ARBITRARY_FEES,
        IDGENERATORTYPE AS ID_GENERATOR_TYPE,
        IDPATTERN AS ID_PATTERN,
        ACCOUNTINGMETHOD AS ACCOUNTING_METHOD,
        DORMANCYPERIODDAYS AS DORMANCY_PERIOD_DAYS,
        OVERDRAFTDAYSINYEAR AS OVERDRAFT_DAYS_IN_YEAR,
        WITHHOLDINGTAXENABLED AS WITHHOLDING_TAX_ENABLED,
        OVERDRAFTINTERESTRATESETTINGSKEY AS OVERDRAFT_INTEREST_RATE_SETTINGS_KEY,
        LINEOFCREDITREQUIREMENT AS LINE_OF_CREDIT_REQUIREMENT,
        INTERESTACCRUEDACCOUNTINGMETHOD AS INTEREST_ACCRUED_ACCOUNTING_METHOD,
        INTERESTDAYSINYEAR AS INTEREST_DAYS_IN_YEAR,
        ALLOWOFFSET AS ALLOW_OFFSET,
       (CASE WHEN MAXIMUMBALANCE = '0E-18' OR MAXIMUMBALANCE = 0 THEN 0.0
             ELSE CAST(MAXIMUMBALANCE AS DECIMAL(18,2)) END) AS MAXIMUM_BALANCE,
        ALLOWTECHNICALOVERDRAFT AS ALLOW_TECHNICAL_OVERDRAFT,
       (CASE WHEN OVERDRAFTINTERESTCALCULATIONBALANCE = '0E-18' OR OVERDRAFTINTERESTCALCULATIONBALANCE = 0 THEN 0.0
             ELSE CAST(OVERDRAFTINTERESTCALCULATIONBALANCE AS DECIMAL(18,2)) END) AS OVERDRAFT_INTEREST_CALCULATION_BALANCE,
        INTERESTSETEXTERNALLYSTARTDATE AS INTEREST_SET_EXTERNALLY_START_DATE,
        INTERESTSETEXTERNALLYENDDATE AS INTEREST_SET_EXTERNALLY_END_DATE,
        INTERESTACCRUALCALCULATION AS INTEREST_ACCRUAL_CALCULATION,
        CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
        TO_TIMESTAMP(MDP_LOAD_DATETIME, 'dd-MMM-yy HH:mm:ss') AS MDP_LOAD_DATETIME,
        __START_AT AS ROW_START_DATETIME,
        __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_mambu_int.savingsproduct
    """
    )
    
    # Define the window specification
    windowSpec = dlf.get_window_spec("ENCODED_KEY","MDP_LOAD_DATETIME")
    df = dlf.get_row_number(df, windowSpec)   
    return df

# COMMAND ----------

@dlt.table(
    name="mambu_saving_transaction", 
    comment="keeps track of all transactions which occur with savings accounts such as state changes, repayments, fees, etc"
)
@dlt.expect("Check that ENCODED_KEY is not null", "ENCODED_KEY IS NOT NULL")
def mambu_saving_transaction():
    df = spark.sql(
        f"""
    SELECT   
        ENCODEDKEY AS ENCODED_KEY,
        BRANCHKEY AS BRANCH_KEY,        
        PRODUCTTYPEKEY AS PRODUCT_TYPE_KEY,
        PARENTACCOUNTKEY AS SAVING_PARENT_ACCOUNT_KEY,
        REVERSALTRANSACTIONKEY AS REVERSAL_TRANSACTION_KEY,
        USERKEY AS USER_KEY,
        TAXRATE_ENCODEDKEY_OID AS TAX_RATE_ENCODEDKEY_OID,
        LINKEDSAVINGSTRANSACTIONKEY AS LINKED_SAVING_TRANSACTION_KEY,
        LINKEDLOANTRANSACTIONKEY AS LINKED_LOAN_TRANSACTION_KEY,
        TILLKEY AS TILL_KEY,
        CENTREKEY AS CENTRE_KEY,
        OVERDRAFT_INDEXRATE_KEY AS OVERDRAFT_INDEX_RATE_KEY,
        TRANSACTIONPERFORMERKEY AS PERFORMER_KEY,
        DETAILS_ENCODEDKEY_OID AS DETAILS_ENCODEDKEY_OID,
        EXTERNALID AS EXTERNAL_ID,
        CAST(TRANSACTIONID AS BIGINT) AS TRANSACTION_ID,
        PAYMENTORDERID AS PAYMENT_ORDER_ID,
        TYPE,
        CAST(BALANCE AS DECIMAL(18,2)) AS BALANCE,
        CAST(AMOUNT AS DECIMAL(18,2)) AS AMOUNT,
        CAST(INTERESTAMOUNT AS DECIMAL(18,2)) AS INTEREST_AMOUNT,   
        CAST(INTERESTRATE AS DECIMAL(18,2)) AS INTEREST_RATE,
        CAST(FUNDSAMOUNT AS DECIMAL(18,2)) AS FUNDS_AMOUNT,
        CAST(FEESAMOUNT AS DECIMAL(18,2)) AS FEES_AMOUNT,
        CAST(CREATIONDATE AS DATE) AS CREATION_DATE,
        CAST(CREATIONDATE AS TIMESTAMP) AS CREATION_DATETIME,
        CAST(ENTRYDATE AS DATE) AS ENTRY_DATE,
        CURRENCYCODE AS CURRENCY_CODE,
        FRACTIONAMOUNT AS FRACTION_AMOUNT,
        OVERDRAFTAMOUNT AS OVERDRAFT_AMOUNT,
        OVERDRAFTFEESAMOUNT AS OVERDRAFT_FEES_AMOUNT,
        OVERDRAFTINTERESTAMOUNT AS OVERDRAFT_INTEREST_AMOUNT,
        OVERDRAFTINTERESTRATE AS OVERDRAFT_INTEREST_RATE,
        OVERDRAFTLIMIT AS OVERDRAFT_LIMIT,
        PRECISEINTERESTAMOUNT AS PRECISE_INTEREST_AMOUNT,
        TECHNICALOVERDRAFTAMOUNT AS TECHNICAL_OVERDRAFT_AMOUNT,
        TECHNICALOVERDRAFTINTERESTAMOUNT AS TECHNICAL_OVERDRAFT_INTEREST_AMOUNT,
        COMMENT,
        MIGRATIONEVENTKEY AS MIGRATION_EVENT_KEY,
        CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
        TO_TIMESTAMP(MDP_LOAD_DATETIME, 'dd-MMM-yy HH:mm:ss') AS MDP_LOAD_DATETIME,
        __START_AT AS ROW_START_DATETIME,
        __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_mambu_int.savingstransaction
    """
    )

    # Define the window specification
    windowSpec = dlf.get_window_spec("ENCODED_KEY","MDP_LOAD_DATETIME")
    df = dlf.get_row_number(df, windowSpec)  
    

    return df

# COMMAND ----------

# MAGIC %md
# MAGIC ----------------------------------------------------------------------
# MAGIC # Mambu TS2-Prove-Point-One (Mortgage Tables -- deployed to Production in August 2025)

# COMMAND ----------

@dlt.table(
    name="mambu_loan_product", 
    comment="stores templates that specify some predefined information and constraints that are then applied to the loan accounts, associated with the loan products. each loan account has to use one product."
)
@dlt.expect("Check that ENCODED_KEY is not null", "ENCODED_KEY IS NOT NULL")
def mambu_loan_product():

    df = spark.sql(
        f"""
    SELECT
        ENCODEDKEY AS ENCODED_KEY,
        ID,
        ACTIVATED, 
        DEFAULTGRACEPERIOD AS DEFAULT_GRACE_PERIOD,
        DEFAULTLOANAMOUNT AS DEFAULT_LOAN_AMOUNT,
        DEFAULTNUMINSTALLMENTS AS DEFAULT_NUM_INSTALLMENTS,
        DEFAULTREPAYMENTPERIODCOUNT AS DEFAULT_REPAYMENT_PERIOD_COUNT,
        GRACEPERIODTYPE AS GRACE_PERIOD_TYPE,
        INTERESTCALCULATIONMETHOD AS INTEREST_CALCULATION_METHOD,
        INTERESTTYPE AS INTEREST_TYPE,
        REPAYMENTSCHEDULEMETHOD AS REPAYMENT_SCHEDULE_METHOD,  
        MAXGRACEPERIOD AS MAX_GRACE_PERIOD,
        MAXLOANAMOUNT AS MAX_LOAN_AMOUNT,
        MAXNUMINSTALLMENTS AS MAX_NUM_INSTALLMENTS,
        MAXPENALTYRATE AS MAX_PENALTY_RATE,
        MINGRACEPERIOD AS MIN_GRACE_PERIOD,
        MINLOANAMOUNT AS MIN_LOAN_AMOUNT,
        MINNUMINSTALLMENTS AS MIN_NUM_INSTALLMENTS,
        MINPENALTYRATE AS MIN_PENALTY_RATE,
        DEFAULTPENALTYRATE AS DEFAULT_PENALTY_RATE,
        PRODUCTDESCRIPTION AS PRODUCT_DESCRIPTION,
        PRODUCTNAME AS PRODUCT_NAME,
        REPAYMENTPERIODUNIT AS REPAYMENT_PERIOD_UNIT,
        PREPAYMENTACCEPTANCE AS PREPAYMENT_ACCEPTANCE,
        INTERESTAPPLICATIONMETHOD AS INTEREST_APPLICATION_METHOD,
        ALLOWARBITRARYFEES AS ALLOW_ARBITRARY_FEES,
        DEFAULTPRINCIPALREPAYMENTINTERVAL AS DEFAULT_PRINCIPAL_REPAYMENT_INTERVAL,
        LOANPENALTYCALCULATIONMETHOD AS LOAN_PENALTY_CALCULATION_METHOD,
        LOANPENALTYGRACEPERIOD AS LOAN_PENALTY_GRACE_PERIOD,
        REPAYMENTCURRENCYROUNDING AS REPAYMENT_CURRENCY_ROUNDING,
        ROUNDINGREPAYMENTSCHEDULEMETHOD AS ROUNDING_REPAYMENTS_SCHEDULE_METHOD,
        PREPAYMENTRECALCULATIONMETHOD AS PREPAYMENT_RECALCULATION_METHOD,
        PRINCIPALPAIDINSTALLMENTSTATUS AS PRINCIPAL_PAID_INSTALLMENT_STATUS,
        DAYSINYEAR AS DAYS_IN_YEAR_METHOD,
        SCHEDULEINTERESTDAYSCOUNTMETHOD AS SCHEDULE_INTEREST_DAYS_COUNT_METHOD,
        REPAYMENTALLOCATIONORDER AS REPAYMENT_ALLOCATION_ORDER,
        IDGENERATORTYPE AS ID_GENERATOR_TYPE,
        IDPATTERN AS ID_PATTERN,
        ACCOUNTINGMETHOD AS ACCOUNTING_METHOD,
        ACCOUNTLINKINGENABLED AS ACCOUNT_LINKING_ENABLED,
        LINKABLESAVINGSPRODUCTKEY AS LINKABLE_SAVINGS_PRODUCT_KEY,
        AUTOLINKACCOUNTS AS AUTO_LINK_ACCOUNTS,
        AUTOCREATELINKEDACCOUNTS AS AUTO_CREATE_LINKED_ACCOUNTS,       
        REPAYMENTSCHEDULEEDITOPTIONS AS REPAYMENT_SCHEDULE_EDIT_OPTIONS,
        SCHEDULEDUEDATESMETHOD AS SCHEDULE_DUE_DATES_METHOD,
        PAYMENTMETHOD AS PAYMENT_METHOD,
        FIXEDDAYSOFMONTH AS FIXED_DAYS_OF_MONTH,
        SHORTMONTHHANDLINGMETHOD AS SHORT_MONTH_HANDLING_METHOD,
        TAXESONINTERESTENABLED AS TAXES_ON_INTEREST_ENABLED,
        TAXSOURCEKEY AS TAX_SOURCE_KEY,
        TAXCALCULATIONMETHOD AS TAX_CALCULATION_METHOD,
        FUTUREPAYMENTSACCEPTANCE AS FUTURE_PAYMENTS_ACCEPTANCE,
        TAXESONFEESENABLED AS TAXES_ON_FEES_ENABLED,
        TAXESONPENALTYENABLED AS TAXES_ON_PENALTY_ENABLED,
        APPLYINTERESTONPREPAYMENTMETHOD AS APPLY_INTEREST_ON_PREPAYMENT_METHOD,
        REPAYMENTELEMENTSROUNDINGMETHOD AS REPAYMENT_SCHEDULE_ROUNDING_METHOD,
        ELEMENTSRECALCULATIONMETHOD AS ELEMENTS_RECALCULATION_METHOD,
        DORMANCYPERIODDAYS AS DORMANCY_PERIOD_DAYS,
        LOCKPERIODDAYS AS LOCK_PERIOD_DAYS,
        CAPPINGMETHOD AS CAPPING_METHOD,
        CAPPINGCONSTRAINTTYPE AS CAPPING_CONSTRAINT_TYPE,
        CAPPINGPERCENTAGE AS CAPPING_PERCENTAGE,
        CAPPINGAPPLYACCRUEDCHARGESBEFORELOCKING AS CAPPING_APPLY_ACCRUED_CHARGES_BEFORE,
        SETTLEMENTOPTIONS AS SETTLEMENT_OPTIONS,
        OFFSETPERCENTAGE AS OFFSET_PERCENTAGE,
        ACCOUNTINITIALSTATE AS ACCOUNT_INITIAL_STATE,
        MAXNUMBEROFDISBURSEMENTTRANCHES AS MAX_NUMBER_OF_DISBURSEMENT_TRANCHES,
        LATEPAYMENTSRECALCULATIONMETHOD AS LATE_PAYMENTS_RECALCULATION_METHOD,
        AMORTIZATIONMETHOD AS AMORTIZATION_METHOD,
        INTERESTRATESETTINGSKEY AS INTEREST_RATE_SETTINGS_KEY,
        LINEOFCREDITREQUIREMENT AS LINE_OF_CREDIT_REQUIREMENT,
        PRODUCTSECURITYSETTINGSKEY AS PRODUCT_SECURITY_SETTINGS_KEY,
        DEFAULTFIRSTREPAYMENTDUEDATEOFFSET AS DEFAULT_FIRST_REPAYMENT_DUEDATE_OFFSET,
        MINFIRSTREPAYMENTDUEDATEOFFSET AS MIN_FIRST_REPAYMENT_DUEDATE_OFFSET,
        MAXFIRSTREPAYMENTDUEDATEOFFSET AS MAX_FIRST_REPAYMENT_DUEDATE_OFFSET,
        INTERESTACCRUEDACCOUNTINGMETHOD AS INTEREST_ACCRUED_ACCOUNTING_METHOD,
        LOANPRODUCTTYPE AS LOAN_PRODUCT_TYPE,
        FORINDIVIDUALS AS FOR_INDIVIDUALS,
        FORPUREGROUPS AS FOR_PURE_GROUPS,
        FORHYBRIDGROUPS AS FOR_HYBRID_GROUPS,
        FORALLBRANCHES AS FOR_ALL_BRANCHES,
        PRINCIPALPAYMENTSETTINGSKEY AS PRINCIPAL_PAYMENT_SETTINGS_KEY,
        REPAYMENTRESCHEDULINGMETHOD AS REPAYMENT_RESCHEDULING_METHOD,
        INTERESTBALANCECALCULATIONMETHOD AS INTEREST_BALANCE_CALCULATION_METHOD,
        ARREARSSETTINGSKEY AS ARREARS_SETTINGS_KEY,
        REDRAWSETTINGSKEY REDRAW_SETTINGS_KEY,
        ALLOWCUSTOMREPAYMENTALLOCATION AS ALLOW_CUSTOM_REPAYMENT_ALLOCATION,
        ACCRUELATEINTEREST AS ACCRUE_LATE_INTEREST,
        INTERESTACCRUALCALCULATION AS INTEREST_ACCRUAL_CALCULATION,
        CATEGORY AS CATEGORY,
        CURRENCYCODE AS CURRENCY_CODE,
        FOUREYESPRINCIPLELOANAPPROVAL AS FOUR_EYES_PRINCIPLE_LOAN_APPROVAL,       
        CAST(CREATIONDATE AS DATE) AS CREATION_DATE,
        CAST(CREATIONDATE AS TIMESTAMP) AS CREATION_DATETIME,
        CAST(LASTMODIFIEDDATE AS DATE) AS LAST_MODIFIED_DATE,
        CAST(LASTMODIFIEDDATE AS TIMESTAMP) AS LAST_MODIFIED_DATETIME,      
        CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
        TO_TIMESTAMP(MDP_LOAD_DATETIME, 'dd-MMM-yy HH:mm:ss') AS MDP_LOAD_DATETIME,
        __START_AT AS ROW_START_DATETIME,
        __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_mambu_int.loanproduct
    """
    )
    
    windowSpec = dlf.get_window_spec("ENCODED_KEY","MDP_LOAD_DATETIME")   
    df = dlf.get_row_number(df, windowSpec)   

    return df

# COMMAND ----------

@dlt.table(
    name="mambu_transaction_details", 
    comment="stores the common details about any financial transaction such as what type of transaction it was, receipt numbers, et"
)
@dlt.expect("Check that ENCODED_KEY is not null", "ENCODED_KEY IS NOT NULL")
def mambu_transaction_details():

    df = spark.sql(
        f"""
    SELECT   
        ENCODEDKEY AS ENCODED_KEY,
        INTERNALTRANSFER AS INTERNAL_TRANSFER,
        TARGETSAVINGSACCOUNTKEY AS TARGET_SAVINGS_ACCOUNT_KEY,
        TRANSACTIONCHANNELKEY AS TRANSACTION_CHANNEL_KEY,
        CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
        TO_TIMESTAMP(MDP_LOAD_DATETIME, 'dd-MMM-yy HH:mm:ss') AS MDP_LOAD_DATETIME,
        TO_TIMESTAMP(MDP_LOAD_DATETIME, 'dd-MMM-yy HH:mm:ss') AS ROW_START_DATETIME,
        TO_TIMESTAMP(NULL, 'dd-MMM-yy HH:mm:ss') AS ROW_END_DATETIME 
    FROM {env_var}_catalog.bronze_mambu_int.transactiondetails
    """
    )
    
    windowSpec = dlf.get_window_spec("ENCODED_KEY","MDP_LOAD_DATETIME")   
    df = dlf.get_row_number(df, windowSpec)   

    return df

# COMMAND ----------

@dlt.table(
    name="mambu_transaction_channel", 
    comment="stores the definition of payment types"
)
@dlt.expect("Check that ENCODED_KEY is not null", "ENCODED_KEY IS NOT NULL")
def mambu_transaction_channel():

    df = spark.sql(
        f"""
    SELECT
        ENCODEDKEY AS ENCODED_KEY,
        ID,
        NAME,
        INDEX,
        CREATEDBYUSERKEY AS CREATED_BY_USER_KEY,
        ACTIVATED,
        SAVINGSCONSTRAINTSUSAGE AS SAVINGS_CONSTRAINTS_USAGE,
        LOANCONSTRAINTSUSAGE AS LOAN_CONSTRAINTS_USAGE,
        USAGERIGHTSKEY AS USAGE_RIGHTS_KEY,
        LOAN_CUSTOM_FILTER_CONSTRAINT_KEY AS LOAN_CUSTOM_FILTER_CONSTRAINT_KEY,
        SAVINGS_CUSTOM_FILTER_CONSTRAINT_KEY AS SAVINGS_CUSTOM_FILTER_CONSTRAINT_KEY,    
        CAST(CREATIONDATE AS DATE) AS CREATION_DATE,
        CAST(CREATIONDATE AS TIMESTAMP) AS CREATION_DATETIME,              
        CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
        TO_TIMESTAMP(MDP_LOAD_DATETIME, 'dd-MMM-yy HH:mm:ss') AS MDP_LOAD_DATETIME,
        __START_AT AS ROW_START_DATETIME,
        __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_mambu_int.transactionchannel
    """
    )
    
    windowSpec = dlf.get_window_spec("ENCODED_KEY","MDP_LOAD_DATETIME")   
    df = dlf.get_row_number(df, windowSpec)   

    return df

# COMMAND ----------

@dlt.table(
    name="mambu_account_interest_rate_settings", 
    comment="stores the mambu account interest rates"
)
@dlt.expect("Check that ENCODED_KEY is not null", "ENCODED_KEY IS NOT NULL")
def mambu_account_interest_rate_settings():

    df = spark.sql(
        f"""
    SELECT   
        ENCODEDKEY AS ENCODED_KEY,
        ACCOUNTKEY AS ACCOUNT_KEY,      
        INTERESTRATETYPE AS INTEREST_RATE_TYPE,
        INDEXSOURCEKEY AS INDEX_SOURCE_KEY,
        INTERESTRATECEILINGVALUE AS INTEREST_RATE_CEILING_VALUE,
        INTERESTRATEFLOORVALUE AS INTEREST_RATE_FLOOR_VALUE,
        INTERESTREVIEWCOUNT AS INTEREST_REVIEW_COUNT,
        INTERESTRATEREVIEWUNIT AS INTEREST_RATE_REVIEW_UNIT,
        INTERESTRATE AS INTEREST_RATE,
        INTERESTSPREAD AS INTEREST_SPREAD,  
        CAST(VALIDFROM AS DATE) AS VALID_FROM_DATE,
        CAST(VALIDFROM AS TIMESTAMP) AS VALID_FROM_DATETIME,    
        CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
        TO_TIMESTAMP(MDP_LOAD_DATETIME, 'dd-MMM-yy HH:mm:ss') AS MDP_LOAD_DATETIME,
        TO_TIMESTAMP(MDP_LOAD_DATETIME, 'dd-MMM-yy HH:mm:ss') AS ROW_START_DATETIME,
        TO_TIMESTAMP(NULL, 'dd-MMM-yy HH:mm:ss') AS ROW_END_DATETIME 
    FROM {env_var}_catalog.bronze_mambu_int.accountinterestratesettings
    """
    )
    
    windowSpec = dlf.get_window_spec("ENCODED_KEY","MDP_LOAD_DATETIME")   
    df = dlf.get_row_number(df, windowSpec)   

    return df

# COMMAND ----------


@dlt.table(
    name="mambu_gl_account", 
    comment="stores the mambu gl account information"
)
@dlt.expect("Check that ENCODED_KEY is not null", "ENCODED_KEY IS NOT NULL")
def mambu_gl_account():

    df = spark.sql(
        f"""
    SELECT   
        ENCODEDKEY AS ENCODED_KEY,
        ACTIVATED,
        CAST(CREATIONDATE AS DATE) AS CREATION_DATE,
        CAST(CREATIONDATE AS TIMESTAMP) AS CREATION_DATETIME,
        DESCRIPTION,
        GLCODE AS GL_CODE,
        CAST(LASTMODIFIEDDATE AS DATE)  AS LAST_MODIFIED_DATE,
        CAST(LASTMODIFIEDDATE AS TIMESTAMP) AS LAST_MODIFIED_DATETIME,
        NAME,
        TYPE,
        USAGE,
        MIGRATIONEVENTKEY AS MIGRATION_EVENT_KEY,
        ALLOWMANUALJOURNALENTRIES AS ALLOW_MANUAL_JOURNAL_ENTRIES,
        STRIPTRAILINGZEROS AS STRIP_TRAILING_ZEROS,
        CURRENCYCODE AS CURRENCY_CODE,
        CAST(MDP_LOAD_ID AS BIGINT) AS MDP_LOAD_ID,
        TO_TIMESTAMP(MDP_LOAD_DATETIME, 'dd-MMM-yy HH:mm:ss') AS MDP_LOAD_DATETIME,
        __START_AT AS ROW_START_DATETIME,
        __END_AT AS ROW_END_DATETIME
    FROM {env_var}_catalog.bronze_mambu_int.glaccount
    """
    )
    
    windowSpec = dlf.get_window_spec("ENCODED_KEY","MDP_LOAD_DATETIME")   
    df = dlf.get_row_number(df, windowSpec)   

    return df
