# Databricks notebook source
import dlt
from pyspark.sql.functions import expr, row_number, monotonically_increasing_id, md5, xxhash64
from pyspark.sql.window import Window
from pyspark.sql import Row
from pyspark.sql.types import *
from datetime import datetime
from pyspark.sql import DataFrame
from pyspark.sql import SparkSession

# Get environment variable from AKV
env_var = dbutils.secrets.get(scope = 'data-kv-scope', key = 'data-platform-environment')

# COMMAND ----------

@dlt.table(
    name = "fact_complaint",
    comment = "the complaint fact table"
)
def gold_fact_complaint():
    # Execute SQL query to select and transform data
    query = f"""
      WITH CTE_CLOSED_BY_DATE AS (
      SELECT
      COMPLAINT_ID,
      EVENT_CREATED_BY AS CLOSED_BY,
      ROW_NUMBER() OVER( PARTITION BY COMPLAINT_ID ORDER BY EVENT_START_DATE ASC) AS ROW_NUM
      FROM {env_var}_catalog.silver_int.enquire_event
      WHERE EVENT_TYPE_ID = 190
      ),

      CTE_COMPLAINT_COST AS (
        SELECT
        cc.COMPLAINT_ID,
        CAST(SUM(cc.COST_AMOUNT) AS DECIMAL(15,2)) AS TOTAL_REDRESS_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 1 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS COMPENSATION_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 2 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS DISTRESS_AND_INCONVENIENCE_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 3 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FREE_TRANSFER_OUT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 4 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS GOODWILL,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 5 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS REFUND_OF_LOST_INTEREST,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 6 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS INTEREST_OF_DELAYED_SETTLEMENT_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 7 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS WAIVED_FEES_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 8 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS WAIVED_INSURANCE_EXCESS_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 9 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS REFUND_OF_PREMIUMS_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 10 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS MATERIAL_LOSS_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 11 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_CASE_FEE,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 12 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_COMPENSATION,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 13 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_DISTRESS_AND_INCONVIENIENCE,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 14 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_FREE_TRANSFER_OUT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 15 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_GOODWILL,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 16 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_REFUND_OF_LOST_INCOME_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 17 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_LOST_INTEREST_COMPENSATION_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 18 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_WAIVED_FEES_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 19 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_WAIVED_INSURANCE_EXCESS_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 20 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_REFUND_OF_PREMIUMS_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 21 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_MATERIAL_LOSS_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 24 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS REFUND_OF_PREMIUM_PLEVIN_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 25 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_REFUND_OF_PLEVIN_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 1001 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS REFUNDED_FEES_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 1002 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS ENDOWMENT_COMPENSATION_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 1003 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS HMRC_TAX_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 1004 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS FOS_HMRC_TAX_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 1005 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS LOST_INTEREST_COMPENSATION_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 1006 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS SIMPLY_SAYING_SORRY_AMOUNT,
        CAST(SUM(CASE WHEN cc.COST_CATEGORY_CODE = 1007 THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS SIMPLY_SAYING_SORRY_POSTAL_AMOUNT,
        CAST(SUM(CASE WHEN ( cc.COST_CATEGORY_CODE IN(1, 12, 1006, 13, 15, 2, 4) AND ct.COMPLAINT_TYPE_ID != 10 AND c.FSA_INDICATOR = 'Y') THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS REPORTABLE_COMPENSATION_AMOUNT,
        CAST(SUM(CASE WHEN ( cc.COST_CATEGORY_CODE IN(9, 20) AND ct.COMPLAINT_TYPE_ID != 10 AND c.FSA_INDICATOR = 'Y') THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS REPORTABLE_REFUNDED_PREMIUM_AMOUNT,
        CAST(SUM(CASE WHEN ( cc.COST_CATEGORY_CODE IN(1005, 1001, 5, 8) AND ct.COMPLAINT_TYPE_ID != 10 AND c.FSA_INDICATOR = 'Y') THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS REPORTABLE_REFUNDED_FEES_INTEREST_AMOUNT,
        CAST(SUM(CASE WHEN ( cc.COST_CATEGORY_CODE IN(1, 12, 1006, 13, 15, 2, 4) AND ct.COMPLAINT_TYPE_ID != 10 AND c.FSA_INDICATOR != 'Y') THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS NON_REPORTABLE_COMPENSATION_AMOUNT,
        CAST(SUM(CASE WHEN ( cc.COST_CATEGORY_CODE IN(9, 20) AND ct.COMPLAINT_TYPE_ID != 10 AND c.FSA_INDICATOR != 'Y') THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS NON_REPORTABLE_REFUNDED_PREMIUM_AMOUNT,
        CAST(SUM(CASE WHEN ( cc.COST_CATEGORY_CODE IN(1005, 1001, 5, 8) AND ct.COMPLAINT_TYPE_ID != 10 AND c.FSA_INDICATOR != 'Y') THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS NON_REPORTABLE_REFUNDED_FEES_INTEREST_AMOUNT,
        CAST(SUM(CASE WHEN ( cc.COST_CATEGORY_CODE IN(1007, 1004, 1003, 11) AND ct.COMPLAINT_TYPE_ID IN(9, 1001) AND c.FSA_INDICATOR != 'Y') THEN cc.COST_AMOUNT ELSE 0 END) AS DECIMAL(15,2)) AS NON_REPORTABLE_IRISH_AND_GIBRALTAR_COSTS_AMOUNT
        FROM {env_var}_catalog.silver_int.enquire_complaint_cost cc
        LEFT JOIN {env_var}_catalog.silver_int.enquire_complaint_cost_category ccc
        ON cc.COST_CATEGORY_CODE = ccc.COST_CATEGORY_ID
        LEFT JOIN {env_var}_catalog.silver_con.enquire_complaint c
        ON cc.COMPLAINT_ID = c.COMPLAINT_ID
        LEFT JOIN {env_var}_catalog.silver_int.enquire_complaint_type ct
        ON c.COMPLAINT_TYPE = ct.COMPLAINT_TYPE_ID
        GROUP BY cc.COMPLAINT_ID
        ORDER BY cc.COMPLAINT_ID DESC
      ),

      CTE_STAGE_ENQUIRE AS (
      SELECT
        CAST(c.COMPLAINT_ID AS BIGINT) AS COMPLAINT_ID,
        PERSON_COMPLAINT_REFERRED_TO,
        THIRD_PARTY_ID,
        PAYMENT_SERVICE_TYPE_ID,
        COMPLAINT_STATUS,
        COMPLAINT_RECEIVED_METHOD_ID,
        xxhash64(CONCAT(
          COALESCE(COMPLAINT_REASON, 'NULL'),
          COALESCE(CAST(REASON_FOR_COMPLAINT_OPTION_1 AS STRING), 'NULL'),
          COALESCE(CAST(REASON_FOR_COMPLAINT_OPTION_2 AS STRING), 'NULL'),
          COALESCE(CAST(REASON_FOR_COMPLAINT_OPTION_3 AS STRING), 'NULL')
        )) AS COMPLAINT_REASON_ID,
        xxhash64(CONCAT(
          COALESCE(CAST(ROOT_CAUSE AS STRING), 'NULL'),
          COALESCE(CAST(ROOT_CAUSE_ANALYSIS_ID AS STRING), 'NULL'),
          COALESCE(CAST(ROOT_CAUSE_ANALYSIS_CATEGORY_ID AS STRING), 'NULL'),
          COALESCE(CAST(ROOT_CAUSE_AREA_ID AS STRING), 'NULL'),
          COALESCE(CAST(ROOT_CAUSE_CHANNEL_ID AS STRING), 'NULL'),
          COALESCE(CAST(ROOT_CAUSE_JOURNEY_ID AS STRING), 'NULL')
        )) AS ROOT_CAUSE_ANALYSIS_ID,
        COMPLAINANT_TYPE_ID,
        COMPLAINT_TYPE,
        JUSTIFIED,
        24HR_COMPLAINT_HOW_RESOLVED_CODE,
        FOS_RESOLUTION,
        FSA_NON_REPORT,
        xxhash64(CONCAT(
            COALESCE(CAST(FSA_ACTUAL_PRODUCT_TYPE AS STRING), 'NULL'),
            COALESCE(CAST(FSA_PRODUCT_TYPE AS STRING), 'NULL')
        )) AS FSA_PRODUCT_TYPE,
        xxhash64(CONCAT(
            COALESCE(CAST(FSA_REPORTING_CATEGORY AS STRING), 'NULL'),
            COALESCE(CAST(FSA_REPORTING_SUB_CATEGORY AS STRING), 'NULL')
        )) AS FSA_REPORTING_CATEGORY,
        xxhash64(CONCAT(
            COALESCE(CAST(CONSUMER_DUTY_OUTCOME_ID AS STRING), 'NULL'),
            COALESCE(CAST(CONSUMER_DUTY_SUB_OUTCOME_ID AS STRING), 'NULL')
        )) AS CONSUMER_DUTY_OUTCOME,
        LAST_CHANGED_DATE,
        CREATED_DATE,
        LAST_CHANGED_BY,
        CREATED_BY,
        CLT_ASSIGNEE,
        FOS_SUBMISSION_ASSIGNED_TO,
        PERSON_RESPONDING_TO_COMPLAINT,
        cbd.CLOSED_BY,
        STAFF_MEMBER_COMPLAINT_AGAINST
      FROM {env_var}_catalog.silver_con.enquire_complaint c
      LEFT JOIN CTE_CLOSED_BY_DATE cbd
        ON c.COMPLAINT_ID = cbd.COMPLAINT_ID
        AND cbd.ROW_NUM = 1
      ),

      CTE_EVENT_RECEIVED_DATE AS (
      SELECT
          COMPLAINT_ID,
          CAST(MIN(EVENT_START_DATE) AS DATE) AS COMPLAINT_RECEIVED_DATE
      FROM {env_var}_catalog.silver_int.enquire_event
      WHERE EVENT_TYPE_ID = 103
      GROUP BY COMPLAINT_ID
      ),

      CTE_EVENT_CLOSED_DATE AS (
      SELECT
          COMPLAINT_ID,
          CAST(MIN(EVENT_END_DATE) AS DATE) AS COMPLAINT_CLOSED_DATE
      FROM {env_var}_catalog.silver_int.enquire_event
      WHERE EVENT_TYPE_ID = 190
      GROUP BY COMPLAINT_ID
      ),

      CTE_RESOLVED_BY_FOS_DATE AS (
      SELECT
          COMPLAINT_ID,
          CAST(MIN(EVENT_END_DATE) AS DATE) AS RESOLVED_BY_FOS_DATE
      FROM {env_var}_catalog.silver_int.enquire_event
      WHERE EVENT_TYPE_ID = 432
      GROUP BY COMPLAINT_ID
      ),

      CTE_REFERRED_TO_FOS_DATE AS (
      SELECT
          COMPLAINT_ID,
          CAST(MIN(EVENT_END_DATE) AS DATE) AS REFFERED_TO_FOS_DATE
      FROM {env_var}_catalog.silver_int.enquire_event
      WHERE EVENT_TYPE_ID = 430
      GROUP BY COMPLAINT_ID
      ),

      CTE_FURTHER_COMPLAINT_RECEIVED_DATE AS (
      SELECT
          COMPLAINT_ID,
          CAST(MIN(EVENT_END_DATE) AS DATE) AS FURTHER_COMPLAINT_RECEIVED_DATE
      FROM {env_var}_catalog.silver_int.enquire_event
      WHERE EVENT_TYPE_ID = 430
      GROUP BY COMPLAINT_ID
      ),

      CTE_FURTHER_COMPLAINT_RESOLVED_DATE AS (
      SELECT
          COMPLAINT_ID,
          CAST(MIN(EVENT_END_DATE) AS DATE) AS FURTHER_COMPLAINT_RESOLVED_DATE
      FROM {env_var}_catalog.silver_int.enquire_event
      WHERE EVENT_TYPE_ID = 430
      GROUP BY COMPLAINT_ID
      ),

      CTE_OWN_DATE AS (
      SELECT
          COMPLAINT_ID,
          CAST(MAX(EVENT_END_DATE) AS DATE) AS OWN_DATE
      FROM {env_var}_catalog.silver_int.enquire_event
      GROUP BY COMPLAINT_ID
      )

      SELECT
          stage.COMPLAINT_ID AS PK_FACT_COMPLAINT,
          CASE 
            WHEN ISNULL(cct.PK_COMPLAINANT_TYPE) = false THEN cct.PK_COMPLAINANT_TYPE
            WHEN ISNULL(cct.PK_COMPLAINANT_TYPE) = true THEN -1
            ELSE -2
          END AS FK_COMPLAINANT_TYPE,
          CASE 
              WHEN ISNULL(ref.PK_COMPLAINT_REFERRED_TO) = false THEN ref.PK_COMPLAINT_REFERRED_TO
              WHEN ISNULL(ref.PK_COMPLAINT_REFERRED_TO) = true THEN -1
              ELSE -2
          END AS FK_COMPLAINT_REFERRED_TO,
          CASE 
            WHEN ISNULL(cs.PK_COMPLAINT_STATUS) = false THEN cs.PK_COMPLAINT_STATUS
            WHEN ISNULL(cs.PK_COMPLAINT_STATUS) = true THEN -1
            ELSE -2
          END AS FK_COMPLAINT_STATUS,
          CASE 
            WHEN ISNULL(ct.PK_COMPLAINT_TYPE) = false THEN ct.PK_COMPLAINT_TYPE
            WHEN ISNULL(ct.PK_COMPLAINT_TYPE) = true THEN -1
            ELSE -2
          END AS FK_COMPLAINT_TYPE,
          CASE 
            WHEN ISNULL(crm.PK_COMPLAINT_RECEIVED_METHOD) = false THEN crm.PK_COMPLAINT_RECEIVED_METHOD
            WHEN ISNULL(crm.PK_COMPLAINT_RECEIVED_METHOD) = true THEN -1
            ELSE -2
          END AS FK_COMPLAINT_RECEIVED_METHOD,
          CASE 
            WHEN ISNULL(cdo.PK_CONSUMER_DUTY_OUTCOME) = false THEN cdo.PK_CONSUMER_DUTY_OUTCOME
            WHEN ISNULL(cdo.PK_CONSUMER_DUTY_OUTCOME) = true THEN -1
            ELSE -2
          END AS FK_CONSUMER_DUTY_OUTCOME,
          CASE 
            WHEN ISNULL(fcr.PK_FOS_CATEGORY_RESOLUTION) = false THEN fcr.PK_FOS_CATEGORY_RESOLUTION
            WHEN ISNULL(fcr.PK_FOS_CATEGORY_RESOLUTION) = true THEN -1
            ELSE -2
          END AS FK_FOS_CATEGORY_RESOLUTION,
          CASE 
            WHEN ISNULL(fpt.PK_FSA_PRODUCT_TYPE) = false THEN fpt.PK_FSA_PRODUCT_TYPE
            WHEN ISNULL(fpt.PK_FSA_PRODUCT_TYPE) = true THEN -1
            ELSE -2
          END AS FK_FSA_PRODUCT_TYPE,
          CASE 
            WHEN ISNULL(frt.PK_FSA_REPORTING_CATEGORY) = false THEN frt.PK_FSA_REPORTING_CATEGORY
            WHEN ISNULL(frt.PK_FSA_REPORTING_CATEGORY) = true THEN -1
            ELSE -2
          END AS FK_FSA_REPORTING_CATEGORY,
          CASE 
            WHEN ISNULL(mor.PK_METHOD_OF_RESOLUTION) = false THEN mor.PK_METHOD_OF_RESOLUTION
            WHEN ISNULL(mor.PK_METHOD_OF_RESOLUTION) = true THEN -1
            ELSE -2
          END AS FK_METHOD_OF_RESOLUTION,
          CASE 
            WHEN ISNULL(j.PK_JUSTIFIED) = false THEN j.PK_JUSTIFIED
            WHEN ISNULL(j.PK_JUSTIFIED) = true THEN -1
            ELSE -2
          END AS FK_JUSTIFIED,
          CASE 
            WHEN ISNULL(nr.PK_NON_REPORTABLE) = false THEN nr.PK_NON_REPORTABLE
            WHEN ISNULL(nr.PK_NON_REPORTABLE) = true THEN -1
            ELSE -2
          END AS FK_NON_REPORTABLE,
          CASE 
            WHEN ISNULL(pst.PK_PAYMENT_SERVICE_TYPE) = false THEN pst.PK_PAYMENT_SERVICE_TYPE
            WHEN ISNULL(pst.PK_PAYMENT_SERVICE_TYPE) = true THEN -1
            ELSE -2
          END AS FK_PAYMENT_SERVICE_TYPE,
          CASE 
            WHEN ISNULL(rca.PK_ROOT_CAUSE_ANALYSIS) = false THEN rca.PK_ROOT_CAUSE_ANALYSIS
            WHEN ISNULL(rca.PK_ROOT_CAUSE_ANALYSIS) = true THEN -1
            ELSE -2
          END AS FK_ROOT_CAUSE_ANALYSIS,
          CASE 
            WHEN ISNULL(cr.PK_COMPLAINT_REASON) = false THEN cr.PK_COMPLAINT_REASON
            WHEN ISNULL(cr.PK_COMPLAINT_REASON) = true THEN -1
            ELSE -2
          END AS FK_COMPLAINT_REASON,
          CASE 
              WHEN ISNULL(thr.PK_COMPLAINT_THIRD_PARTY) = false THEN thr.PK_COMPLAINT_THIRD_PARTY
              WHEN ISNULL(thr.PK_COMPLAINT_THIRD_PARTY) = true THEN -1
              ELSE -2
          END AS FK_COMPLAINT_THIRD_PARTY,
          CASE 
              WHEN ISNULL(dc.PK_COMPLAINT) = false THEN dc.PK_COMPLAINT
              WHEN ISNULL(dc.PK_COMPLAINT) = true THEN -1
              ELSE -2
          END AS FK_COMPLAINT,
          CASE 
              WHEN ISNULL(dcf.PK_COMPLAINT_FLAG) = false THEN dcf.PK_COMPLAINT_FLAG
              WHEN ISNULL(dcf.PK_COMPLAINT_FLAG) = true THEN -1
              ELSE -2
          END AS FK_COMPLAINT_FLAG,
          CAST(COALESCE(erd.COMPLAINT_RECEIVED_DATE, '19000-01-01') AS DATE) AS FK_RECEIVED_DATE,
          CAST(COALESCE(ecd.COMPLAINT_CLOSED_DATE, '1900-01-01') AS DATE) AS FK_DEFINITIVE_CLOSURE_DATE,
          CAST(COALESCE(rfd.RESOLVED_BY_FOS_DATE, '1900-01-01') AS DATE) AS FK_RESOLVED_BY_FOS_DATE,
          CAST(COALESCE(rtd.REFFERED_TO_FOS_DATE, '1900-01-01') AS DATE) AS FK_REFERRED_TO_FOS_DATE,
          CAST(COALESCE(fcrd.FURTHER_COMPLAINT_RECEIVED_DATE, '1900-01-01') AS DATE) AS FK_FURTHER_COMPLAINT_RECEIVED_DATE,
          CAST(COALESCE(fcrd2.FURTHER_COMPLAINT_RESOLVED_DATE, '1900-01-01') AS DATE) AS FK_FURTHER_COMPLAINT_RESOLVED_DATE,
          CAST(COALESCE(stage.LAST_CHANGED_DATE, '1900-01-01') AS DATE) AS FK_LAST_CHANGED_DATE,
          CAST(COALESCE(od.OWN_DATE, '1900-01-01') AS DATE) AS FK_OWN_DATE,
          CAST(COALESCE(stage.CREATED_DATE, '1900-01-01') AS DATE) AS FK_CREATED_DATE,
          CASE 
              WHEN ISNULL(stage.LAST_CHANGED_BY) = false THEN stage.LAST_CHANGED_BY
              WHEN ISNULL(stage.LAST_CHANGED_BY) = true THEN '-1'
              ELSE '-2'
          END AS FK_STAFF_LAST_CHANGED_BY,
          CASE 
              WHEN ISNULL(stage.CREATED_BY) = false THEN stage.CREATED_BY
              WHEN ISNULL(stage.CREATED_BY) = true THEN '-1'
              ELSE '-2'
          END AS FK_STAFF_CREATED_BY,
          CASE 
              WHEN ISNULL(stage.CLT_ASSIGNEE) = false THEN stage.CLT_ASSIGNEE
              WHEN ISNULL(stage.CLT_ASSIGNEE) = true THEN '-1'
              ELSE '-2'
          END AS FK_STAFF_ASSIGNED_TO,
          CASE 
              WHEN ISNULL(stage.CLT_ASSIGNEE) = false THEN stage.CLT_ASSIGNEE
              WHEN ISNULL(stage.CLT_ASSIGNEE) = true THEN '-1'
              ELSE '-2'
          END AS FK_STAFF_FOS_SUBMISSION_ASSIGNEE,
          CASE 
              WHEN ISNULL(stage.PERSON_RESPONDING_TO_COMPLAINT) = false THEN stage.PERSON_RESPONDING_TO_COMPLAINT
              WHEN ISNULL(stage.PERSON_RESPONDING_TO_COMPLAINT) =  true THEN '-1'
              ELSE '-2'
          END AS FK_STAFF_RESPONDING_TO_COMPLAINT,
          CASE 
              WHEN ISNULL(stage.CLOSED_BY) = false THEN stage.CLOSED_BY
              WHEN ISNULL(stage.CLOSED_BY) = true THEN '-1'
              ELSE '-2'
          END AS FK_STAFF_CLOSED_BY,
          CASE 
              WHEN ISNULL(stage.STAFF_MEMBER_COMPLAINT_AGAINST) = false THEN stage.STAFF_MEMBER_COMPLAINT_AGAINST
              WHEN ISNULL(stage.STAFF_MEMBER_COMPLAINT_AGAINST) = true THEN '-1'
              ELSE '-2'
          END AS FK_STAFF_COMPLAINT_AGAINST,
        COALESCE(ccc.COMPENSATION_AMOUNT, '0.00') AS COMPENSATION_AMOUNT,
        COALESCE(ccc.DISTRESS_AND_INCONVENIENCE_AMOUNT, '0.00') AS DISTRESS_AND_INCONVENIENCE_AMOUNT,
        COALESCE(ccc.FREE_TRANSFER_OUT, '0.00') AS FREE_TRANSFER_OUT,
        COALESCE(ccc.GOODWILL, '0.00') AS GOODWILL,
        COALESCE(ccc.REFUND_OF_LOST_INTEREST, '0.00') AS REFUND_OF_LOST_INTEREST,
        COALESCE(ccc.INTEREST_OF_DELAYED_SETTLEMENT_AMOUNT, '0.00') AS INTEREST_OF_DELAYED_SETTLEMENT_AMOUNT,
        COALESCE(ccc.WAIVED_FEES_AMOUNT, '0.00') AS WAIVED_FEES_AMOUNT,
        COALESCE(ccc.WAIVED_INSURANCE_EXCESS_AMOUNT, '0.00') AS WAIVED_INSURANCE_EXCESS_AMOUNT,
        COALESCE(ccc.REFUND_OF_PREMIUMS_AMOUNT, '0.00') AS REFUND_OF_PREMIUMS_AMOUNT,
        COALESCE(ccc.MATERIAL_LOSS_AMOUNT, '0.00') AS MATERIAL_LOSS_AMOUNT,
        COALESCE(ccc.FOS_CASE_FEE, '0.00') AS FOS_CASE_FEE,
        COALESCE(ccc.FOS_COMPENSATION, '0.00') AS FOS_COMPENSATION,
        COALESCE(ccc.FOS_DISTRESS_AND_INCONVIENIENCE, '0.00') FOS_DISTRESS_AND_INCONVIENIENCE,
        COALESCE(ccc.FOS_FREE_TRANSFER_OUT, '0.00') AS FOS_FREE_TRANSFER_OUT,
        COALESCE(ccc.FOS_GOODWILL, '0.00') AS FOS_GOODWILL,
        COALESCE(ccc.FOS_REFUND_OF_LOST_INCOME_AMOUNT, '0.00') AS FOS_REFUND_OF_LOST_INCOME_AMOUNT,
        COALESCE(ccc.FOS_LOST_INTEREST_COMPENSATION_AMOUNT, '0.00') AS FOS_LOST_INTEREST_COMPENSATION_AMOUNT,
        COALESCE(ccc.FOS_WAIVED_FEES_AMOUNT, '0.00') AS FOS_WAIVED_FEES_AMOUNT,
        COALESCE(ccc.FOS_WAIVED_INSURANCE_EXCESS_AMOUNT, '0.00') AS FOS_WAIVED_INSURANCE_EXCESS_AMOUNT,
        COALESCE(ccc.FOS_REFUND_OF_PREMIUMS_AMOUNT, '0.00') AS FOS_REFUND_OF_PREMIUMS_AMOUNT,
        COALESCE(ccc.FOS_MATERIAL_LOSS_AMOUNT, '0.00') AS FOS_MATERIAL_LOSS_AMOUNT,
        COALESCE(ccc.REFUND_OF_PREMIUM_PLEVIN_AMOUNT, '0.00') AS REFUND_OF_PREMIUM_PLEVIN_AMOUNT,
        COALESCE(ccc.FOS_REFUND_OF_PLEVIN_AMOUNT, '0.00') AS FOS_REFUND_OF_PLEVIN_AMOUNT,
        COALESCE(ccc.REFUNDED_FEES_AMOUNT, '0.00') AS REFUNDED_FEES_AMOUNT,
        COALESCE(ccc.ENDOWMENT_COMPENSATION_AMOUNT, '0.00') AS ENDOWMENT_COMPENSATION_AMOUNT,
        COALESCE(ccc.HMRC_TAX_AMOUNT, '0.00') AS HMRC_TAX_AMOUNT,
        COALESCE(ccc.FOS_HMRC_TAX_AMOUNT, '0.00') AS FOS_HMRC_TAX_AMOUNT,
        COALESCE(ccc.LOST_INTEREST_COMPENSATION_AMOUNT, '0.00') AS LOST_INTEREST_COMPENSATION_AMOUNT,
        COALESCE(ccc.SIMPLY_SAYING_SORRY_AMOUNT, '0.00') AS SIMPLY_SAYING_SORRY_AMOUNT,
        COALESCE(ccc.SIMPLY_SAYING_SORRY_POSTAL_AMOUNT, '0.00') AS SIMPLY_SAYING_SORRY_POSTAL_AMOUNT,
        COALESCE(ccc.REPORTABLE_COMPENSATION_AMOUNT, '0.00') AS REPORTABLE_COMPENSATION_AMOUNT,
        COALESCE(ccc.REPORTABLE_REFUNDED_PREMIUM_AMOUNT, '0.00') AS REPORTABLE_REFUNDED_PREMIUM_AMOUNT,
        COALESCE(ccc.REPORTABLE_REFUNDED_FEES_INTEREST_AMOUNT, '0.00') AS REPORTABLE_REFUNDED_FEES_INTEREST_AMOUNT,
        COALESCE(ccc.NON_REPORTABLE_COMPENSATION_AMOUNT, '0.00') AS NON_REPORTABLE_COMPENSATION_AMOUNT,
        COALESCE(ccc.NON_REPORTABLE_REFUNDED_PREMIUM_AMOUNT, '0.00') AS NON_REPORTABLE_REFUNDED_PREMIUM_AMOUNT,
        COALESCE(ccc.NON_REPORTABLE_REFUNDED_FEES_INTEREST_AMOUNT, '0.00') AS NON_REPORTABLE_REFUNDED_FEES_INTEREST_AMOUNT,
        COALESCE(ccc.NON_REPORTABLE_IRISH_AND_GIBRALTAR_COSTS_AMOUNT, '0.00') AS NON_REPORTABLE_IRISH_AND_GIBRALTAR_COSTS_AMOUNT
      FROM CTE_STAGE_ENQUIRE stage
      LEFT JOIN {env_var}_catalog.gold_con.dim_complaint_referred_to ref
      ON stage.PERSON_COMPLAINT_REFERRED_TO = ref.BK_COMPLAINT_REFERRED_TO
      AND ref.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_con.dim_complaint_third_party thr
      ON stage.THIRD_PARTY_ID = thr.BK_COMPLAINT_THIRD_PARTY
      AND thr.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_payment_service_type pst
      ON stage.PAYMENT_SERVICE_TYPE_ID = pst.BK_PAYMENT_SERVICE_TYPE
      AND pst.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_complaint_status cs
      ON stage.COMPLAINT_STATUS = cs.BK_COMPLAINT_STATUS
      AND cs.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_complaint_received_method crm
      ON stage.COMPLAINT_RECEIVED_METHOD_ID = crm.BK_COMPLAINT_RECEIVED_METHOD
      AND crm.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_complaint_reason cr
      ON stage.COMPLAINT_REASON_ID = cr.BK_COMPLAINT_REASON
      AND cr.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_complaint_complainant_type cct
      ON stage.COMPLAINANT_TYPE_ID = cct.BK_COMPLAINANT_TYPE
      AND cct.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_complaint_type ct
      ON stage.COMPLAINT_TYPE = ct.BK_COMPLAINT_TYPE
      AND ct.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_justified j
      ON stage.JUSTIFIED = j.BK_JUSTIFIED
      AND j.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_method_of_resolution mor
      ON stage.24HR_COMPLAINT_HOW_RESOLVED_CODE = mor.BK_METHOD_OF_RESOLUTION
      AND mor.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_fos_category_resolution fcr
      ON stage.FOS_RESOLUTION = fcr.BK_FOS_CATEGORY_RESOLUTION
      AND fcr.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_non_reportable nr
      ON stage.FSA_NON_REPORT = nr.BK_NON_REPORTABLE
      AND nr.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_root_cause_analysis rca
      ON stage.ROOT_CAUSE_ANALYSIS_ID = rca.BK_ROOT_CAUSE_ANALYSIS
      AND rca.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_FSA_product_type fpt
      ON stage.FSA_PRODUCT_TYPE = fpt.BK_FSA_PRODUCT_TYPE
      AND fpt.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_FSA_reporting_category frt
      ON stage.FSA_REPORTING_CATEGORY = frt.BK_FSA_REPORTING_CATEGORY
      AND frt.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_consumer_duty_outcome cdo
      ON stage.CONSUMER_DUTY_OUTCOME = cdo.BK_CONSUMER_DUTY_OUTCOME
      AND cdo.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_con.dim_complaint dc
      ON stage.COMPLAINT_ID = dc.BK_COMPLAINT
      AND dc.ROW_IS_CURRENT = 1
      LEFT JOIN {env_var}_catalog.gold_int.dim_complaint_flag dcf
      ON stage.COMPLAINT_ID = dcf.BK_COMPLAINT
      AND dc.ROW_IS_CURRENT = 1
      LEFT JOIN CTE_EVENT_RECEIVED_DATE erd
      ON stage.COMPLAINT_ID = erd.COMPLAINT_ID
      LEFT JOIN CTE_EVENT_CLOSED_DATE ecd
      ON stage.COMPLAINT_ID = ecd.COMPLAINT_ID
      LEFT JOIN CTE_RESOLVED_BY_FOS_DATE rfd
      ON stage.COMPLAINT_ID = rfd.COMPLAINT_ID
      LEFT JOIN CTE_REFERRED_TO_FOS_DATE rtd
      ON stage.COMPLAINT_ID = rtd.COMPLAINT_ID
      LEFT JOIN CTE_FURTHER_COMPLAINT_RECEIVED_DATE fcrd
      ON stage.COMPLAINT_ID = fcrd.COMPLAINT_ID
      LEFT JOIN CTE_FURTHER_COMPLAINT_RESOLVED_DATE fcrd2
      ON stage.COMPLAINT_ID = fcrd2.COMPLAINT_ID
      LEFT JOIN CTE_OWN_DATE od
      ON stage.COMPLAINT_ID = od.COMPLAINT_ID
      LEFT JOIN CTE_COMPLAINT_COST ccc
      ON stage.COMPLAINT_ID = ccc.COMPLAINT_ID
    """
    df = spark.sql(query)
    
    return df

# COMMAND ----------

@dlt.table(
    name = "fact_complaint_event",
    comment = "the complaint event fact table"
)
def gold_fact_complaint_event():
    # Execute SQL query to select and transform data
    query = f"""
    WITH CTE_STAGE_EVENT AS (
    SELECT
    EVENT_ID,
    EVENT_TYPE_ID,
    COMPLAINT_ID,
    CAST(COALESCE(EVENT_START_DATE, '1900-01-01') AS DATE) AS FK_EVENT_START_DATE,
    CAST(COALESCE(EVENT_END_DATE, '1900-01-01') AS DATE) AS FK_EVENT_END_DATE
    FROM {env_var}_catalog.silver_int.enquire_event
    )

    SELECT
        EVENT_ID AS PK_FACT_COMPLAINT_EVENT, 
        CASE 
            WHEN ISNULL(cet.PK_COMPLAINT_EVENT_TYPE) = false THEN cet.PK_COMPLAINT_EVENT_TYPE
            WHEN ISNULL(cet.PK_COMPLAINT_EVENT_TYPE) = true THEN -1
            ELSE -2
        END AS FK_COMPLAINT_EVENT_TYPE,
        CASE 
            WHEN ISNULL(c.PK_COMPLAINT) = false THEN c.PK_COMPLAINT
            WHEN ISNULL(c.PK_COMPLAINT) = true THEN -1
            ELSE -2
        END AS FK_COMPLAINT,
        stage.FK_EVENT_START_DATE,
        stage.FK_EVENT_END_DATE
    FROM CTE_STAGE_EVENT stage
    LEFT JOIN {env_var}_catalog.gold_int.dim_complaint_event_type cet
    ON stage.EVENT_TYPE_ID = cet.BK_COMPLAINT_EVENT_TYPE
    AND cet.ROW_IS_CURRENT = 1
    LEFT JOIN {env_var}_catalog.gold_con.dim_complaint c
    ON stage.COMPLAINT_ID = c.BK_COMPLAINT
    AND c.ROW_IS_CURRENT = 1
    """
    df = spark.sql(query)
    
    return df

# COMMAND ----------

@dlt.table(
    name = "fact_complaint_cost",
    comment = "the complaint cost fact table"
)
def gold_fact_complaint_cost():
    # Execute SQL query to select and transform data
    query = f"""
    WITH CTE_STAGE_COST AS (
    SELECT
    COMPLAINT_COST_ID,
    COMPLAINT_ID,
    COST_CATEGORY_CODE,
    CAST(COALESCE(COST_PAID_DATE, '1900-01-01') AS DATE) AS FK_COST_PAID_DATE,
    COST_CURRENCY,
    COST_AMOUNT
    FROM {env_var}_catalog.silver_int.enquire_complaint_cost
    )

    SELECT
        COMPLAINT_COST_ID AS PK_FACT_COMPLAINT_COST, 
        CASE 
            WHEN ISNULL(ct.PK_COST_CATEGORY) = false THEN ct.PK_COST_CATEGORY
            WHEN ISNULL(ct.PK_COST_CATEGORY) = true THEN -1
            ELSE -2
        END AS FK_COST_CATEGORY,
        CASE 
            WHEN ISNULL(c.PK_COMPLAINT) = false THEN c.PK_COMPLAINT
            WHEN ISNULL(c.PK_COMPLAINT) = true THEN -1
            ELSE -2
        END AS FK_COMPLAINT,
        FK_COST_PAID_DATE,
        COST_CURRENCY,
        stage.COST_AMOUNT AS REDRESS_AMOUNT_ORIGINAL_CURRENCY
    FROM CTE_STAGE_COST stage
    LEFT JOIN {env_var}_catalog.gold_int.dim_cost_category ct
    ON stage.COST_CATEGORY_CODE = ct.BK_COST_CATEGORY
    AND ct.ROW_IS_CURRENT = 1
    LEFT JOIN {env_var}_catalog.gold_con.dim_complaint c
    ON stage.COMPLAINT_ID = c.BK_COMPLAINT
    AND c.ROW_IS_CURRENT = 1
    """
    df = spark.sql(query)
    
    return df
