SELECT
  a.APPLICANT_ID AS BK_MORTGAGE_APPLICANT,
  '{job_name}' AS SOURCE_SYSTEM,
  a.ROW_START_DATETIME AS ROW_START_DATETIME,
  a.ROW_END_DATETIME AS ROW_END_DATETIME,
  CASE
    WHEN ROW_END_DATETIME IS NULL THEN 1
    ELSE 0
  END AS ROW_IS_CURRENT
FROM {env_var}_catalog.silver_con.mso_applicant a
WHERE a.ROW_END_DATETIME IS NULL -- Current rows only