SELECT
u.USERS_ID AS BK_WORKFLOW_USER,
COALESCE(u.FULL_NAME, 'Unknown') AS USER_NAME,
CASE WHEN u.IS_DELETED = 1 THEN 'Yes' 
  WHEN u.IS_DELETED = 0 THEN 'No' ELSE 'Unknown' END AS IS_DELETED,
'SPECTRA' AS SOURCE_SYSTEM,
getdate () AS ROW_START_DATETIME,
CAST(NULL AS TIMESTAMP) AS ROW_END_DATETIME,
1 AS ROW_IS_CURRENT
FROM {env_var}_catalog.silver_con.spectra_users u
;