# Databricks notebook source
import dlt
from pyspark.sql.functions import expr, row_number, xxhash64, lit, to_timestamp
from pyspark.sql.window import Window
from pyspark.sql import Row
from pyspark.sql.types import *
from datetime import datetime
from pyspark.sql import DataFrame
from pyspark.sql import SparkSession

import mdp_databricks_common.gold_layer_functions as dlf

# Get environment variable from AKV
env_var = dbutils.secrets.get(scope = 'data-kv-scope', key = 'data-platform-environment')
mdp_gold_layer_processed_datetime = datetime.now()

# COMMAND ----------

@dlt.table(
    name = "dim_mortgage_product",
    comment = "the mortgage product dimension which is at product code level."
)
def gold_dim_mortgage_product():
    # Execute SQL query to select and transform data
    query = f"""
    ( 
    SELECT 
    lps.PRODUCT_CODE AS BK_MORTGAGE_PRODUCT,
    IFNULL(PRODUCT_DESCRIPTION,'Unknown') AS PRODUCT_DESCRIPTION,
    CAST(IFNULL(CAST(LAUNCH_DATE AS DATE),'1900-01-01') AS DATE) AS LAUNCH_DATE,
    CAST(IFNULL(CAST(WITHDRAWAL_DATE AS DATE),'1900-01-01') AS DATE) AS WITHDRAWAL_DATE,
    IFNULL(PRODUCT_STATUS,'Unknown') AS PRODUCT_STATUS,
    IFNULL(LENDING_SEGMENT,'Unknown') AS LENDING_SEGMENT,
    IFNULL(lps.RISK_CATEGORY,'Unknown') AS RISK_CATEGORY_CODE,
    IFNULL(ls.REPORTING_CATEGORY,'Unknown') AS REPORTING_CATEGORY,
    IFNULL(RISK_CATEGORY_NARR,'Unknown') AS RISK_CATEGORY_NARRATIVE,
    IFNULL(
        CASE 
            WHEN ANCHOR_SEGMENT_FLAG = 'Y' THEN 'Yes'
            WHEN ANCHOR_SEGMENT_FLAG = 'N' THEN 'No'
            ELSE ANCHOR_SEGMENT_FLAG 
        END,
    'Unknown') AS HAS_ANCHOR_SEGMENT,
    CAST(LOCK_IN_PERIOD_YEARS AS INT) AS LOCK_IN_PERIOD_YEARS,
    CASE 
           WHEN LOCK_IN_PERIOD_YEARS = '0' THEN 'No Lock' 
           WHEN LOCK_IN_PERIOD_YEARS = 'N/A' THEN 'No Lock' 
           WHEN LOCK_IN_PERIOD_YEARS > '0' THEN 'Lock' 
           ELSE 'Unknown' 
    END AS LOCK_IN,
    CAST(CASHBACK_AMOUNT AS DECIMAL(10,2)) AS CASHBACK_AMOUNT,
    CAST(MAXIMUM_CASHBACK_AMOUNT AS DECIMAL(10,2)) AS MAXIMUM_CASHBACK_AMOUNT,
    IFNULL(TYPE,'Unknown') AS PRODUCT_TYPE,
    CAST(COMPLETION_FEE AS DECIMAL(10,2)) AS COMPLETION_FEE,
    CAST(PROCESSING_FEES AS DECIMAL(10,2)) AS PROCESSING_FEES,
    IFNULL(
        CASE 
            WHEN IS_VALUATION_FREE = 'Y' THEN 'Yes' 
            WHEN IS_VALUATION_FREE = 'N' THEN 'No'
            ELSE IS_VALUATION_FREE
        END, 
    'Unknown') AS IS_VALUATION_FREE,
    IFNULL(
        CASE 
            WHEN IS_LEGALS_FREE = 'Y' THEN 'Yes' 
            WHEN IS_LEGALS_FREE = 'N' THEN 'No'
            ELSE IS_LEGALS_FREE
        END, 
    'Unknown') AS IS_LEGALS_FREE,
    CAST(BEHAVIOURAL_LIFE_PROFILE AS DECIMAL(10,3)) AS BEHAVIOURAL_LIFE_PROFILE,
    CAST(COST_OF_VALUATION AS DECIMAL(10,2)) AS COST_OF_VALUATION,
    CAST(VALUATION_FEE_INCOME AS DECIMAL(10,2)) AS VALUATION_FEE_INCOME,
    CAST(PRODUCT_TRANSFER_ECONOMIC_VALUE_ADD AS DECIMAL(20,15)) AS PRODUCT_TRANSFER_ECONOMIC_VALUE_ADD,
    CAST(WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD AS DECIMAL(20,15)) AS WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD,
    CAST(WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_IRB AS DECIMAL(20,15)) AS WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_IRB,
    CAST(TERM_YEARS AS DECIMAL(10,3)) AS PRODUCT_TERM ,
    CAST(IFNULL(CAST(IF_FIXED_END_DATE AS DATE),'1900-01-01') AS DATE) AS FIXED_RATE_PRODUCT_END_DATE,
    IFNULL(REPAYMENT_METHOD,'Unknown') AS PAYMENT_TYPE,
    IFNULL(REPORT_TYPE,'Unknown') AS INTEREST_BASIS,
    CAST(MINIMUM_LTV_PERCENT AS DECIMAL(10,3)) AS MINIMUM_LTV_PERCENT,
    CAST(MAXIMUM_LTV_PERCENT AS DECIMAL(10,3)) AS MAXIMUM_LTV_PERCENT,
    ESTIMATED_LOAN_SIZE AS ESTIMATED_LOAN_SIZE,
    CAST(BORROWER_SHARE_PER AS DECIMAL(10,2)) AS BORROWER_SHARE_PERCENTAGE,
    CAST(LIQUIDITY_TERM_PREMIUM AS DECIMAL(20,10)),
    IFNULL(
    CASE
        WHEN COMPLETION_FEE= 0 or COMPLETION_FEE IS NULL and (CASHBACK_AMOUNT  = 0 or COMPLETION_FEE IS NULL) THEN 'No Fee'
        WHEN COMPLETION_FEE <=  499 AND CASHBACK_AMOUNT = 0 THEN  'Low Completion Fee'
        WHEN COMPLETION_FEE <=  1999 AND CASHBACK_AMOUNT  = 0  THEN 'Low Completion Fee'
        WHEN COMPLETION_FEE <=  999 AND CASHBACK_AMOUNT  = 0 THEN 'Medium Completion Fee'
        WHEN COMPLETION_FEE <=  4999 AND CASHBACK_AMOUNT  = 0 THEN 'Medium Completion Fee'
        WHEN COMPLETION_FEE >= 1499 AND CASHBACK_AMOUNT  = 0  THEN  'High Completion Fee'
        WHEN COMPLETION_FEE >= 5999 AND CASHBACK_AMOUNT  = 0  THEN  'High Completion Fee'
        WHEN COMPLETION_FEE =  0  AND CASHBACK_AMOUNT  <= 250 THEN  'Low Cashback Fee'
        WHEN COMPLETION_FEE <=  0 AND CASHBACK_AMOUNT  <= 500 THEN 'Medium Cashback Fee'
        WHEN COMPLETION_FEE <=  0  AND CASHBACK_AMOUNT  >= 1000 THEN 'High Cashback Fee'
        WHEN COMPLETION_FEE > 0 AND  CASHBACK_AMOUNT  > 0 THEN 'Other' 
        ELSE 'Other'
    END, 'Unknown') AS FEE_CATEGORY,
    IFNULL(CASE 
        WHEN UPPER(PRODUCT_DESCRIPTION) LIKE '%EC %' THEN 'Yes'
        WHEN UPPER(PRODUCT_DESCRIPTION) LIKE '%BR %' THEN 'Yes'
        WHEN UPPER(PRODUCT_DESCRIPTION) LIKE '%CUSTOMER CARE%' THEN 'Yes'
        WHEN UPPER(PRODUCT_DESCRIPTION) LIKE '%EXISTING CUSTOMER%' THEN 'Yes'
        ELSE 'No' 
    END, 'Unknown') AS HAS_CUSTOMER_CARE,
    IFNULL(CASE WHEN UPPER(PRODUCT_DESCRIPTION) LIKE '%WELCOME%' THEN 'Yes' ELSE 'No' END,'Unknown') AS HAS_WELCOME_MORTGAGE,
    IFNULL(CASE WHEN RANK1_BASE_RATE = 'Administered' THEN 'Yes' ELSE 'No' END,'Unknown') AS HAS_DISCOUNT_REVERSION_RATE,
    CAST((STD_STRESSED_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT*0.07) + (STD_STRESSED_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT*0.93) AS DECIMAL(20,15)) AS STD_STR_PT_RETURN_ON_RISK_ADJUSTED_CAPITAL,
    CAST((STD_STRESSED_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT*0.07) + (STD_STRESSED_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT*0.93) AS DECIMAL(20,15)) AS STD_STR_WOL_RETURN_ON_RISK_ADJUSTED_CAPITAL,
    CAST((STD_STRESSED_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT*0.07) + (STD_STRESSED_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT*0.93) AS DECIMAL(20,15)) AS STD_STR_WOL_EXPECTED_LOSS,        
    CAST((STD_STRESSED_CAPITAL_WEIGHTING_DIRECT*0.1) + (STD_STRESSED_CAPITAL_WEIGHTING_INDIRECT*0.9) AS DECIMAL(20,15)) AS STD_STR_CAPITAL_WEIGHTING,         
    CAST((IRB_IFRS9_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT*0.07) + (IRB_IFRS9_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT*0.93) AS DECIMAL(20,15)) AS IRB_IFRS9_PRODUCT_TERM_ECONOMIC_VALUE_ADD,   
    CAST((IRB_IFRS9_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT*0.07) + (IRB_IFRS9_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT*0.93) AS DECIMAL(20,15)) AS IRB_IFRS9_WOL_ECONOMIC_VALUE_ADD,  
    CAST((IRB_IFRS9_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT*0.07) + (IRB_IFRS9_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT*0.93) AS DECIMAL(20,15)) AS IRB_IFRS9_PT_RETURN_ON_RISK_ADJUSTED_CAPITAL,    
    CAST((IRB_IFRS9_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT*0.07) + (IRB_IFRS9_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT*0.93) AS DECIMAL(20,15)) AS IRB_IFRS9_WOL_RETURN_ON_RISK_ADJUSTED_CAPITAL,       
    CAST((IRB_IFRS9_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT*0.07) + (IRB_IFRS9_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT*0.93) AS DECIMAL(20,15)) AS IRB_IFRS9_WOL_EXPECTED_LOSS, 
    CAST((STD_STRESSED_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT*0.07) + (STD_STRESSED_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT*0.93) AS DECIMAL(20,15)) AS STD_STR_WOL_ECONOMIC_VALUE_ADD,    
    CAST((STD_STRESSED_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT*0.07) + (STD_STRESSED_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT*0.93) AS DECIMAL(20,15)) AS STD_STR_PT_ECONOMIC_VALUE_ADD,     
    CAST((IRB_IFRS9_CAPITAL_WEIGHTING_DIRECT*0.1) + (IRB_IFRS9_CAPITAL_WEIGHTING_INDIRECT*0.9) AS DECIMAL(20,15)) AS IRB_IFRS9_CAPITAL_WEIGHTING,       
    CAST((STF_CEN_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT*0.07) + (STD_CEN_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT*0.93) AS DECIMAL(20,15)) AS STD_CEN_PT_ECONOMIC_VALUE_ADD,     
    CAST((STD_CEN_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT*0.07) + (STD_CEN_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT*0.93) AS DECIMAL(20,15)) AS STD_CEN_WOL_ECONOMIC_VALUE_ADD,    
    CAST((STD_CEN_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT*0.07) + (STD_CEN_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT*0.93) AS DECIMAL(20,15)) AS STD_CEN_PT_RETURN_ON_RISK_ADJUSTED_CAPITAL, 
    CAST((STD_CEN_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT*0.07) + (STD_CEN_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT*0.93) AS DECIMAL(20,15)) AS STD_CEN_WOL_RETURN_ON_RISK_ADJUSTED_CAPITAL,
    CAST((STD_CEN_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT*0.07) + (STD_CEN_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT*0.93) AS DECIMAL(20,15)) AS STD_CEN_WOL_EXPECTED_LOSS,   
    CAST((STD_CEN_CAPITAL_WEIGHTING_DIRECT*0.1) + (STD_CEN_CAPITAL_WEIGHTING_INDIRECT*0.9) AS DECIMAL(20,15)) AS STD_CEN_CAPITAL_WEIGHTING,        
    CAST(IRB_IFRS9_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT,   
    CAST(IRB_IFRS9_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT,   
    CAST(IRB_IFRS9_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT,
    CAST(IRB_IFRS9_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT,
    CAST(IRB_IFRS9_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT,
    CAST(STD_CEN_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT AS DECIMAL(20,15)) AS STD_CEN_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT,
    CAST(STD_CEN_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT  AS DECIMAL(20,15)) AS STD_CEN_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT,
    CAST(STD_CEN_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT AS DECIMAL(20,15)) AS STD_CEN_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT,   
    CAST(STD_STRESSED_CAPITAL_WEIGHTING_INDIRECT AS DECIMAL(20,15)) AS STD_STRESSED_CAPITAL_WEIGHTING_INDIRECT,
    CAST(STF_CEN_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT AS DECIMAL(20,15)) AS STD_CEN_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT,    
    CAST(STD_STRESSED_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT AS DECIMAL(20,15)) AS STD_STRESSED_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT,
    CAST(STD_STRESSED_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT AS DECIMAL(20,15)) AS STD_STRESSED_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT,
    CAST(STD_STRESSED_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT AS DECIMAL(20,15)) AS STD_STRESSED_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT,
    CAST(STD_STRESSED_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT AS DECIMAL(20,15)) AS STD_STRESSED_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT,
    CAST(STD_STRESSED_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT  AS DECIMAL(20,15)) AS STD_STRESSED_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT, 
    CAST(STD_STRESSED_CAPITAL_WEIGHTING_DIRECT AS DECIMAL(20,15)) AS STD_STRESSED_CAPITAL_WEIGHTING_DIRECT,
    CAST(STD_STRESSED_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT AS DECIMAL(20,15)) AS STD_STRESSED_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT,
    CAST(STD_STRESSED_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT AS DECIMAL(20,15)) AS STD_STRESSED_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT,
    CAST(STD_STRESSED_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT AS DECIMAL(20,15)) AS STD_STRESSED_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT,
    CAST(STD_STRESSED_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT AS DECIMAL(20,15)) AS STD_STRESSED_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT,
    CAST(STD_STRESSED_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT AS DECIMAL(20,15)) AS STD_STRESSED_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT,    
    CAST(STD_CEN_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT AS DECIMAL(20,15)) AS STD_CEN_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT,
    CAST(STD_CEN_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT AS DECIMAL(20,15)) AS STD_CEN_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT,
    CAST(STD_CEN_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT  AS DECIMAL(20,15))AS STD_CEN_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT,
    CAST(STD_CEN_CAPITAL_WEIGHTING_DIRECT AS DECIMAL(20,15)) AS STD_CEN_CAPITAL_WEIGHTING_DIRECT,
    CAST(STD_CEN_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT AS DECIMAL(20,15))  AS STD_CEN_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT,
    CAST(STD_CEN_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT AS DECIMAL(20,15)) AS STD_CEN_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT,
    CAST(STD_CEN_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT AS DECIMAL(20,15)) AS STD_CEN_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT,
    CAST(IRB_IFRS9_CAPITAL_WEIGHTING_INDIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_CAPITAL_WEIGHTING_INDIRECT,
    CAST(IRB_IFRS9_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT,   
    CAST(IRB_IFRS9_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT,
    CAST(IRB_IFRS9_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT,
    CAST(IRB_IFRS9_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT,
    CAST(IRB_IFRS9_CAPITAL_WEIGHTING_DIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_CAPITAL_WEIGHTING_DIRECT,
    CAST(IRB_IFRS9_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT AS DECIMAL(20,15)) AS IRB_IFRS9_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT,
    CAST(STD_CEN_CAPITAL_WEIGHTING_INDIRECT AS DECIMAL(20,15)) AS STD_CEN_CAPITAL_WEIGHTING_INDIRECT,
    IFNULL(
        CASE 
            WHEN IS_COLLEAGUE_MORTGAGE_SCHEME = 'N' THEN 'No' 
            WHEN IS_COLLEAGUE_MORTGAGE_SCHEME = 'Y' THEN 'Yes'
            ELSE IS_COLLEAGUE_MORTGAGE_SCHEME 
        END, 
'Unknown')  AS IS_STAFF_MORTGAGE,
IFNULL(
    CASE 
        WHEN RISK_BASED_PRICING_FLAG = 'N' THEN 'No' 
        WHEN RISK_BASED_PRICING_FLAG = 'Y' THEN 'Yes'
        ELSE RISK_BASED_PRICING_FLAG 
    END, 
'Unknown') AS HAS_RISK_BASED_PRICING,
    CASE
        WHEN RISK_CATEGORY_NARRATIVE IN (
            'Vanilla', 'Help To Buy', 'First Homes', 'Shared Equity', 'Right To Buy',
            'Retirement Interest Only Mortgage', 'Shared Ownership', 'Interest Only',
            'Interest Only Part & Part', 'Interest Part & Part', 'Contractor', 'Offset',
            'Offshore Tracker (Excluding Buy To Let)', 'Welcome Mortgage',
            'Hundred Percent Lending', 'Lending Into Retirement', 'Self Certification',
            'Shared Ownership Sub Prime', 'Sub Prime', 'First Homes'
        ) THEN 'High Purpose'
        WHEN RISK_CATEGORY_NARRATIVE IN ('Second Home', 'Holiday Let') THEN 'Medium Purpose'
        ELSE 'Low Purpose'
    END AS PURPOSE_LENDING_LEVEL,
    CAST(lps.APPLICATION_FEE AS DECIMAL(20,15)) AS APPLICATION_FEE,
    (CASE WHEN lps.BUSINESS_SOURCE IS NULL THEN 'Unknown' ELSE lps.BUSINESS_SOURCE END) AS BUSINESS_SOURCE,
    CAST(lps.CASHBACK_PERCENTAGE AS DECIMAL(20,15)) AS CASHBACK_PERCENTAGE,
    (CASE WHEN UPPER(lps.COST_OF_RETAIL) IN ('UNKNOWN','NULL') THEN NULL 
          ELSE CAST(lps.COST_OF_RETAIL AS DECIMAL(20,15)) END) AS COST_OF_RETAIL,
    (CASE WHEN lps.IS_FIRST_TIME_BUYER = 'N' THEN 'No' 
          WHEN lps.IS_FIRST_TIME_BUYER = 'Y' THEN 'Yes'
          ELSE 'Unknown' END) AS IS_FIRST_TIME_BUYER, 
    (CASE WHEN lps.FIXED_OR_ROLL IS NULL THEN 'Unknown' ELSE lps.FIXED_OR_ROLL END) AS FIXED_OR_ROLL,
    (CASE WHEN lps.IS_HOME_MOVER = 'N' THEN 'No' 
          WHEN lps.IS_HOME_MOVER = 'Y' THEN 'Yes'
          ELSE 'Unknown' END) AS IS_HOME_MOVER,
    CAST(IFNULL(CAST(lps.LOCK_IN_END_DATE AS DATE),'1900-01-01') AS DATE) AS LOCK_IN_END_DATE,
    CAST(lps.LIQUIDITY_RISK_PREMIUM AS DECIMAL(20,15)) AS LIQUIDITY_RISK_PREMIUM,
    CAST(lps.MAXIUMUM_OVERPAYMENT_ALLOWED AS DECIMAL(20,15)) AS MAXIUMUM_OVERPAYMENT_ALLOWED,
    (CASE WHEN lps.MONTHS_INTEREST IS NULL THEN 'Unknown' ELSE lps.MONTHS_INTEREST END) AS MONTHS_INTEREST,
    TRY_CAST((CASE WHEN QUARTERLY_SWAP_BENCHMARK_PERCENTAGE = 'Unknown' THEN NULL ELSE REPLACE(QUARTERLY_SWAP_BENCHMARK_PERCENTAGE,"%","") END) AS DECIMAL(20,15)) AS QUARTERLY_SWAP_BENCHMARK_PERCENTAGE,
    (CASE WHEN lps.REDEMPTION_CONDITIONS_NARRATIVE IS NULL THEN 'Unknown' ELSE lps.REDEMPTION_CONDITIONS_NARRATIVE END) AS REDEMPTION_CONDITIONS_NARRATIVE,
    (CASE WHEN lps.RETURN_OF_CASHBACK = 'N' THEN 'No' 
          WHEN lps.RETURN_OF_CASHBACK = 'Y' THEN 'Yes'
          ELSE 'Unknown'
     END) AS RETURN_OF_CASHBACK,
    CAST(lps.RETURN_ON_CAPITAL_ROC AS DECIMAL(20,15)) AS RETURN_ON_CAPITAL_ROC,
    (CASE WHEN lps.LOCK_IN_FIXED_ROLL IS NULL THEN 'Unknown' ELSE lps.LOCK_IN_FIXED_ROLL END) AS LOCK_IN_FIXED_ROLL,
    (CASE WHEN lps.IS_REMORTGAGE = 'N' THEN 'No' 
          WHEN lps.IS_REMORTGAGE = 'Y' THEN 'Yes'
          ELSE 'Unknown'
     END) AS IS_REMORTGAGE,
    CAST(lps.TOTAL_FEES AS DECIMAL(20,15)) AS TOTAL_FEES,
    CAST(lps.BENCHMARK_RATE AS DECIMAL(20,15)) AS BENCHMARK_RATE,
    (CASE WHEN lps.APPLICANT_TYPE IS NULL THEN 'Unknown' ELSE lps.APPLICANT_TYPE END) AS APPLICANT_TYPE,
    (CASE WHEN lps.IS_AVAILABLE_ENGLAND = 'N' THEN 'No' 
          WHEN lps.IS_AVAILABLE_ENGLAND = 'Y' THEN 'Yes'
          ELSE 'Unknown'
     END) AS IS_AVAILABLE_ENGLAND,
    (CASE WHEN lps.IS_AVAILABLE_NORTHERN_IRELAND = 'N' THEN 'No' 
          WHEN lps.IS_AVAILABLE_NORTHERN_IRELAND = 'Y' THEN 'Yes'
          ELSE 'Unknown'
     END) AS IS_AVAILABLE_NORTHERN_IRELAND,
    (CASE WHEN lps.IS_AVAILABLE_SCOTLAND = 'N' THEN 'No' 
          WHEN lps.IS_AVAILABLE_SCOTLAND = 'Y' THEN 'Yes'
          ELSE 'Unknown'
     END) AS IS_AVAILABLE_SCOTLAND,
    (CASE WHEN lps.IS_AVAILABLE_TO_CSU = 'N' THEN 'No' 
          WHEN lps.IS_AVAILABLE_TO_CSU = 'Y' THEN 'Yes'
          ELSE 'Unknown'
     END) AS IS_AVAILABLE_TO_CSU,
    (CASE WHEN lps.IS_AVAILABLE_WALES = 'N' THEN 'No' 
          WHEN lps.IS_AVAILABLE_WALES = 'Y' THEN 'Yes'
          ELSE 'Unknown'
     END) AS IS_AVAILABLE_WALES,
    (CASE WHEN lps.IS_DIRECT_TO_CUSTOMER = 'N' THEN 'No' 
          WHEN lps.IS_DIRECT_TO_CUSTOMER = 'Y' THEN 'Yes'
          ELSE 'Unknown'
     END) AS IS_DIRECT_TO_CUSTOMER,
    (CASE WHEN lps.IS_E_COMMERCE IS NULL THEN 'Unknown' ELSE lps.IS_E_COMMERCE END) AS IS_E_COMMERCE,
    (CASE WHEN lps.IS_FREE_MORTGAGE_INDEMNITY_GUARANTEE = 'N' THEN 'No' 
          WHEN lps.IS_FREE_MORTGAGE_INDEMNITY_GUARANTEE = 'Y' THEN 'Yes'
          ELSE 'Unknown'
     END) AS IS_FREE_MORTGAGE_INDEMNITY_GUARANTEE,
    (CASE WHEN lps.IS_GREEN = 'N' THEN 'No' 
          WHEN lps.IS_GREEN = 'Y' THEN 'Yes'
          ELSE 'Unknown'
     END) AS IS_GREEN,
    CAST(lps.HEADLINE_RATE AS DECIMAL(20,15)) AS HEADLINE_RATE,
    (CASE WHEN lps.LOAN_PURPOSE IS NULL THEN 'Unknown' ELSE lps.LOAN_PURPOSE END) AS LOAN_PURPOSE,
    CAST(lps.MAXIMUM_LOAN_AMOUNT AS DECIMAL(20,15)) AS MAXIMUM_LOAN_AMOUNT,
    CAST(lps.OFFER_PERIOD_FUNDING_ANNUAL_PERCENT AS DECIMAL(20,15)) AS OFFER_PERIOD_FUNDING_ANNUAL_PERCENT,
    CAST(lps.OFFER_PERIOD_FUNDING_QUARTERLY_PERCENT AS DECIMAL(20,15)) AS OFFER_PERIOD_FUNDING_QUARTERLY_PERCENT,
    CAST(lps.POST_OFFER_BENCHMARK AS DECIMAL(20,15)) AS POST_OFFER_BENCHMARK,
    CAST(lps.POST_OFFER_FUNDING_RATE_PERCENT AS DECIMAL(20,15)) AS POST_OFFER_FUNDING_RATE_PERCENT,
    CAST(lps.PRODUCT_TARGET_COMPENSATION AS DECIMAL(20,15)) AS PRODUCT_TARGET_COMPENSATION,
    CAST(lps.PRODUCT_TERM_APR AS DECIMAL(20,15)) AS PRODUCT_TERM_APR,
    CAST(lps.RETURN_ON_CAPITAL_DIRECT AS DECIMAL(20,15)) AS RETURN_ON_CAPITAL_DIRECT,
    CAST(lps.RETURN_ON_CAPITAL_INDIRECT AS DECIMAL(20,15)) AS RETURN_ON_CAPITAL_INDIRECT,
    CAST(lps.TRANCHE_SIZE AS DECIMAL(20,15)) AS TRANCHE_SIZE,
    lps.MDP_LOAD_ID,
    lps.MDP_LOAD_DATETIME,
    lps.ROW_IS_CURRENT,
    lps.ROW_START_DATETIME, 
    lps.ROW_END_DATETIME
    FROM {env_var}_catalog.silver_int.lps_product lps
    LEFT JOIN {env_var}_catalog.silver_int.reference_data_lending_segments ls
    ON lps.RISK_CATEGORY = ls.RISK_CATEGORY
    AND ls.ROW_IS_CURRENT = 1
    WHERE lps.ROW_IS_CURRENT = 1)

    """

    df = spark.sql(query)

    # Add the surrogate key and gold layer audit column
    df = df.withColumns({
        "PK_MORTGAGE_PRODUCT": xxhash64("BK_MORTGAGE_PRODUCT"),
        "MDP_GOLD_LAYER_PROCESSED_DATETIME": to_timestamp(lit(mdp_gold_layer_processed_datetime))
        })

    # Select columns explicitly to make PK_ the first column
    df = df.select(
    "PK_MORTGAGE_PRODUCT",
    "BK_MORTGAGE_PRODUCT",
    "PRODUCT_DESCRIPTION",
    "LAUNCH_DATE",
    "WITHDRAWAL_DATE",
    "PRODUCT_STATUS",
    "LENDING_SEGMENT",
    "RISK_CATEGORY_CODE",
    "REPORTING_CATEGORY",
    "RISK_CATEGORY_NARRATIVE",
    "HAS_ANCHOR_SEGMENT",
    "LOCK_IN",
    "LOCK_IN_PERIOD_YEARS",
    "CASHBACK_AMOUNT",
    "MAXIMUM_CASHBACK_AMOUNT",
    "PRODUCT_TYPE",
    "COMPLETION_FEE",
    "PROCESSING_FEES",
    "IS_VALUATION_FREE",
    "IS_LEGALS_FREE",
    "BEHAVIOURAL_LIFE_PROFILE",
    "COST_OF_VALUATION",
    "VALUATION_FEE_INCOME",
    "PRODUCT_TRANSFER_ECONOMIC_VALUE_ADD",
    "WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD",
    "WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_IRB",
    "PRODUCT_TERM",
    "FIXED_RATE_PRODUCT_END_DATE",
    "PAYMENT_TYPE",
    "INTEREST_BASIS",
    "MINIMUM_LTV_PERCENT",
    "MAXIMUM_LTV_PERCENT",
    "ESTIMATED_LOAN_SIZE",
    "BORROWER_SHARE_PERCENTAGE",
    "LIQUIDITY_TERM_PREMIUM",
    "FEE_CATEGORY",
    "HAS_CUSTOMER_CARE",
    "HAS_WELCOME_MORTGAGE",
    "HAS_DISCOUNT_REVERSION_RATE",
    "STD_STR_PT_RETURN_ON_RISK_ADJUSTED_CAPITAL",
    "STD_STR_WOL_RETURN_ON_RISK_ADJUSTED_CAPITAL",
    "STD_STR_WOL_EXPECTED_LOSS",
    "STD_STR_CAPITAL_WEIGHTING",         
    "IRB_IFRS9_PRODUCT_TERM_ECONOMIC_VALUE_ADD",   
    "IRB_IFRS9_WOL_ECONOMIC_VALUE_ADD",  
    "IRB_IFRS9_PT_RETURN_ON_RISK_ADJUSTED_CAPITAL",    
    "IRB_IFRS9_WOL_RETURN_ON_RISK_ADJUSTED_CAPITAL",       
    "IRB_IFRS9_WOL_EXPECTED_LOSS", 
    "STD_STR_WOL_ECONOMIC_VALUE_ADD",    
    "STD_STR_PT_ECONOMIC_VALUE_ADD",     
    "IRB_IFRS9_CAPITAL_WEIGHTING",       
    "STD_CEN_PT_ECONOMIC_VALUE_ADD",     
    "STD_CEN_WOL_ECONOMIC_VALUE_ADD",    
    "STD_CEN_PT_RETURN_ON_RISK_ADJUSTED_CAPITAL", 
    "STD_CEN_WOL_RETURN_ON_RISK_ADJUSTED_CAPITAL",
    "STD_CEN_WOL_EXPECTED_LOSS",   
    "STD_CEN_CAPITAL_WEIGHTING",        
    "IRB_IFRS9_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT",   
    "IRB_IFRS9_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT",  
    "IRB_IFRS9_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT", 
    "IRB_IFRS9_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT",
    "IRB_IFRS9_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT",
    "STD_CEN_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT", 
    "STD_CEN_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT",   
    "STD_CEN_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT",    
    "STD_STRESSED_CAPITAL_WEIGHTING_INDIRECT",
    "STD_CEN_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT",    
    "STD_STRESSED_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT",
    "STD_STRESSED_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT",
    "STD_STRESSED_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT",
    "STD_STRESSED_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT",  
    "STD_STRESSED_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT",   
    "STD_STRESSED_CAPITAL_WEIGHTING_DIRECT",
    "STD_STRESSED_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT",  
    "STD_STRESSED_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT", 
    "STD_STRESSED_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT", 
    "STD_STRESSED_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_DIRECT",   
    "STD_STRESSED_PRODUCT_TERM_ECONOMIC_VALUE_ADD_DIRECT",     
    "STD_CEN_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT",
    "STD_CEN_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT",
    "STD_CEN_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT",
    "STD_CEN_CAPITAL_WEIGHTING_DIRECT",
    "STD_CEN_WHOLE_OF_LIFE_EXPECTED_LOSS_DIRECT",
    "STD_CEN_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT",
    "STD_CEN_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_DIRECT",   
    "IRB_IFRS9_CAPITAL_WEIGHTING_INDIRECT",
    "IRB_IFRS9_WHOLE_OF_LIFE_EXPECTED_LOSS_INDIRECT",    
    "IRB_IFRS9_PRODUCT_TERM_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT",
    "IRB_IFRS9_WHOLE_OF_LIFE_ECONOMIC_VALUE_ADD_INDIRECT",
    "IRB_IFRS9_PRODUCT_TERM_ECONOMIC_VALUE_ADD_INDIRECT",
    "IRB_IFRS9_CAPITAL_WEIGHTING_DIRECT", 
    "IRB_IFRS9_WHOLE_OF_LIFE_RETURN_ON_RISK_ADJUSTED_CAPITAL_INDIRECT",
    "STD_CEN_CAPITAL_WEIGHTING_INDIRECT",
    "IS_STAFF_MORTGAGE",
    "HAS_RISK_BASED_PRICING",
    "PURPOSE_LENDING_LEVEL",
    "APPLICATION_FEE",
    "BUSINESS_SOURCE",
    "CASHBACK_PERCENTAGE",
    "COST_OF_RETAIL",
    "IS_FIRST_TIME_BUYER", 
    "FIXED_OR_ROLL",
    "IS_HOME_MOVER",
    "LOCK_IN_END_DATE",
    "LIQUIDITY_RISK_PREMIUM",
    "MAXIUMUM_OVERPAYMENT_ALLOWED",
    "MONTHS_INTEREST",
    "QUARTERLY_SWAP_BENCHMARK_PERCENTAGE",
    "REDEMPTION_CONDITIONS_NARRATIVE",
    "RETURN_OF_CASHBACK",
    "RETURN_ON_CAPITAL_ROC",
    "LOCK_IN_FIXED_ROLL",
    "IS_REMORTGAGE",
    "TOTAL_FEES",
    "BENCHMARK_RATE",
    "APPLICANT_TYPE",
    "IS_AVAILABLE_ENGLAND",
    "IS_AVAILABLE_NORTHERN_IRELAND",
    "IS_AVAILABLE_SCOTLAND",
    "IS_AVAILABLE_TO_CSU",
    "IS_AVAILABLE_WALES",
    "IS_DIRECT_TO_CUSTOMER",
    "IS_E_COMMERCE",
    "IS_FREE_MORTGAGE_INDEMNITY_GUARANTEE",
    "IS_GREEN",
    "HEADLINE_RATE",
    "LOAN_PURPOSE",
    "MAXIMUM_LOAN_AMOUNT",
    "OFFER_PERIOD_FUNDING_ANNUAL_PERCENT",
    "OFFER_PERIOD_FUNDING_QUARTERLY_PERCENT",
    "POST_OFFER_BENCHMARK",
    "POST_OFFER_FUNDING_RATE_PERCENT",
    "PRODUCT_TARGET_COMPENSATION",
    "PRODUCT_TERM_APR",
    "RETURN_ON_CAPITAL_DIRECT",
    "RETURN_ON_CAPITAL_INDIRECT",
    "TRANCHE_SIZE",
    "MDP_LOAD_ID",
    "MDP_LOAD_DATETIME",
    "ROW_IS_CURRENT",
    "ROW_START_DATETIME", 
    "ROW_END_DATETIME",
    "MDP_GOLD_LAYER_PROCESSED_DATETIME"
    )

    # Insert dummy values for unknown(-1) and nulls(-2)
    df = dlf.insert_dimension_dummy_rows(df)

    return df

# COMMAND ----------

@dlt.table(
    name = "dim_mortgage_product_rank",
    comment = "Dimension at the grain of product code and rank, containing mortgage product rank details."
)
def gold_dim_mortgage_product_rank():
    # Execute SQL query to select and transform data
    query = f"""
        WITH cte_mortgage_product_rank AS (
        SELECT
            PRODUCT_CODE
            ,1 AS RANK
            ,RANK1_TYPE AS TYPE
            ,RANK1_BASE_RATE AS BASE_RATE_TYPE
            ,RANK1_RATE_PER AS RATE
            ,RANK1_PRODUCT_TERM_GROUP AS PRODUCT_TERM_GROUP
            ,RANK1_TRACKING_RATE AS TRACKING_RATE
            ,RANK1_FLOOR_RATE_PER As MINIMUM_RATE
            ,RANK1_CEIL_RATE_PER AS MAXIMUM_RATE
            ,RANK1_FOR_MONTHS AS MONTHS_DURATION
            ,MDP_LOAD_ID
            ,MDP_LOAD_DATETIME
            ,ROW_START_DATETIME
            ,ROW_END_DATETIME
            ,ROW_IS_CURRENT
        FROM silver_int.lps_product

        UNION ALL

        SELECT
            PRODUCT_CODE
            ,2 AS RANK
            ,RANK2_TYPE AS TYPE
            ,RANK2_BASE_RATE AS BASE_RATE_TYPE
            ,RANK2_RATE_PER AS RATE
            ,RANK2_PRODUCT_TERM_GROUP AS PRODUCT_TERM_GROUP
            ,RANK2_TRACKING_RATE AS TRACKING_RATE
            ,RANK2_FLOOR_RATE_PER As MINIMUM_RATE
            ,RANK2_CEIL_RATE_PER AS MAXIMUM_RATE
            ,RANK2_FOR_MONTHS AS MONTHS_DURATION
            ,MDP_LOAD_ID
            ,MDP_LOAD_DATETIME
            ,ROW_START_DATETIME
            ,ROW_END_DATETIME
            ,ROW_IS_CURRENT
        FROM silver_int.lps_product

        UNION ALL

        SELECT
            PRODUCT_CODE
            ,3 AS RANK
            ,RANK3_TYPE AS TYPE
            ,RANK3_BASE_RATE AS BASE_RATE_TYPE
            ,RANK3_RATE_PER AS RATE
            ,RANK3_PRODUCT_TERM_GROUP AS PRODUCT_TERM_GROUP
            ,RANK3_TRACKING_RATE AS TRACKING_RATE
            ,RANK3_FLOOR_RATE_PER As MINIMUM_RATE
            ,RANK3_CEIL_RATE_PER AS MAXIMUM_RATE
            ,RANK3_FOR_MONTHS AS MONTHS_DURATION
            ,MDP_LOAD_ID
            ,MDP_LOAD_DATETIME
            ,ROW_START_DATETIME
            ,ROW_END_DATETIME
            ,ROW_IS_CURRENT
        FROM silver_int.lps_product

        UNION ALL

        SELECT
            PRODUCT_CODE
            ,4 AS RANK
            ,RANK4_TYPE AS TYPE
            ,RANK4_BASE_RATE AS BASE_RATE_TYPE
            ,RANK4_RATE_PER AS RATE
            ,RANK4_PRODUCT_TERM_GROUP AS PRODUCT_TERM_GROUP
            ,RANK4_TRACKING_RATE AS TRACKING_RATE
            ,RANK4_FLOOR_RATE_PER As MINIMUM_RATE
            ,RANK4_CEIL_RATE_PER AS MAXIMUM_RATE
            ,RANK4_FOR_MONTHS AS MONTHS_DURATION
            ,MDP_LOAD_ID
            ,MDP_LOAD_DATETIME
            ,ROW_START_DATETIME
            ,ROW_END_DATETIME
            ,ROW_IS_CURRENT
        FROM silver_int.lps_product

        UNION ALL

        SELECT
            PRODUCT_CODE
            ,5 AS RANK
            ,RANK5_TYPE AS TYPE
            ,RANK5_BASE_RATE AS BASE_RATE_TYPE
            ,RANK5_RATE_PER AS RATE
            ,RANK5_PRODUCT_TERM_GROUP AS PRODUCT_TERM_GROUP
            ,RANK5_TRACKING_RATE AS TRACKING_RATE
            ,RANK5_FLOOR_RATE_PER As MINIMUM_RATE
            ,RANK5_CEIL_RATE_PER AS MAXIMUM_RATE
            ,RANK5_FOR_MONTHS AS MONTHS_DURATION
            ,MDP_LOAD_ID
            ,MDP_LOAD_DATETIME
            ,ROW_START_DATETIME
            ,ROW_END_DATETIME
            ,ROW_IS_CURRENT
        FROM silver_int.lps_product)
        SELECT
            xxhash64(CONCAT(CAST(mpr.product_code AS STRING), CAST(mpr.RANK AS STRING))) AS PK_MORTGAGE_PRODUCT_RANK
            ,mpr.product_code AS BK_MORTGAGE_PRODUCT_RANK
            ,mpr.RANK AS RANK
            ,COALESCE(CAST(mpr.TYPE AS STRING), 'Unknown') AS TYPE
            ,COALESCE(CAST(mpr.BASE_RATE_TYPE AS STRING), 'Unknown') AS BASE_RATE_TYPE
            ,COALESCE(CAST(mpr.RATE AS DECIMAL(38,6)), '-2') AS RATE
            ,COALESCE(CAST(mpr.PRODUCT_TERM_GROUP AS STRING), 'Unknown') AS PRODUCT_TERM_GROUP
            ,'Unknown' AS PRODUCT_RATE_TYPE --stub as cannot determine source as of yet
            ,COALESCE(CAST(mpr.TRACKING_RATE AS STRING), 'Unknown') AS TRACKING_RATE
            ,COALESCE(mpr.MINIMUM_RATE, '-2') AS MINIMUM_RATE
            ,COALESCE(mpr.MAXIMUM_RATE, '-2') AS MAXIMUM_RATE
            ,COALESCE(mpr.MONTHS_DURATION, '-2') AS  MONTHS_DURATION
            ,mpr.MDP_LOAD_ID
            ,mpr.MDP_LOAD_DATETIME
            ,mpr.ROW_START_DATETIME
            ,mpr.ROW_END_DATETIME
            ,mpr.ROW_IS_CURRENT
        FROM cte_mortgage_product_rank mpr
        WHERE TYPE IS NOT NULL 
    """

    df = spark.sql(query)

    # Add gold layer audit column
    df = df.withColumns({
        "MDP_GOLD_LAYER_PROCESSED_DATETIME": to_timestamp(lit(mdp_gold_layer_processed_datetime))
        })

    # Insert dummy values for unknown(-1) and nulls(-2)
    df = dlf.insert_dimension_dummy_rows(df)

    return df
